<?php

/**
 * Description of FilterHelper
 *
 * @author Yanet
 */

namespace MyCp\mycpBundle\Helpers;

class FilterHelper {

    const ACCOMMODATION_TOP20 = 1;
    const ACCOMMODATION_SELECTION = 2;
    const ACCOMMODATION_INMEDIATE_BOOKING = 3;
    const ACCOMMODATION_NOT_RECOMMENDABLE = 4;
    const ACCOMMODATION_WITH_ERRORS_PHONE = 5;
    const ACCOMMODATION_WITH_ERRORS_ADDRESS = 6;
    const ACCOMMODATION_WITH_NO_PHOTOS = 7;
    const ACCOMMODATION_WITH_NO_OWNER_PHOTO = 8;
    const ACCOMMODATION_PHOTOS_LESS_5 = 9;
    const ACCOMMODATION_INFO_GENERAL = 10;
    const ACCOMMODATION_INFO_ROOMS = 11;
    const ACCOMMODATION_INFO_TRANSLATE = 12;
    const ACCOMMODATION_INFO_INACTIVE_ROOMS = 13;
    const ACCOMMODATION_INFO_NO_PHONE_OR_MOBILE = 14;
    const ACCOMMODATION_INFO_NO_EMAIL = 15;
    const ACCOMMODATION_ERROR_GEOLOCALIZATION = 16;
    const ACCOMMODATION_TRANSLATION_AUTOMATIC = 17;
    const ACCOMMODATION_CUBACOUPON = 18;

}

?>
