# To catch all outdated routes of the old website the routing
# for website migration must be included first!
frontend_website_migration:
    resource: "@FrontEndBundle/Resources/config/routingFrontendWebsiteMigration.yml"

backend_login_check:
    pattern:  /backend/login_check
backend_login:
    pattern:  /backend/login/
    defaults: { _controller: mycpBundle:Public:login }
backend_logout:
    pattern: /backend/logout

mycp:
    resource: "@mycpBundle/Resources/config/routing.yml"
    prefix:   /

mycp_sitemap:
    path: /sitemap.{_format}
    defaults: { _controller: FrontEndBundle:Public:site_map }

mycp_simple_details:
    pattern:  /{own_code}/
    defaults: { _controller: FrontEndBundle:Ownership:own_details_direct }

mycp_own_details:
    pattern:  /simple/{mycp_code}/
    defaults: { _controller: FrontEndBundle:Ownership:simple }

mycp_frontend:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    type: be_simple_i18n

frontend_ckeck:
    pattern:  /user/check
frontend_login:
    pattern:  /{_locale}/login/
    defaults: { _controller: FrontEndBundle:Public:login }
frontend_logout:
    pattern: /user/logout

mycp_welcome_main:
    pattern:  /welcome/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: en }

mycp_main:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: en }

frontend_change_currency:
    pattern:  /change_currency/{curr_code}
    defaults: { _controller: FrontEndBundle:Currency:change_currency }

