mycp:
    resource: "@mycpBundle/Resources/config/routing.yml"
    prefix:   /

mycp_own_details:
    pattern:  /{own_code}
    defaults: { _controller: frontEndBundle:ownership:own_details_direct }

mycp_frontend:
    resource: "@frontEndBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    type: be_simple_i18n

frontend_ckeck:
    pattern:  /check
frontend_login:
    pattern:  /login/
    defaults: { _controller: frontEndBundle:public:login }
frontend_logout:
    pattern: /logout

backend_login_check:
    pattern:  /backend/login_check
backend_login:
    pattern:  /backend/login/
    defaults: { _controller: mycpBundle:Public:login }
backend_logout:
    pattern: /backend/logout

mycp_welcome_main:
    pattern:  /welcome/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: es }

mycp_main:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: es }

_imagine:
    resource: .
    type: imagine

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal



