backend_login_check:
    pattern:  /backend/login_check
backend_login:
    pattern:  /backend/login/
    defaults: { _controller: mycpBundle:Public:login }
backend_logout:
    pattern: /backend/logout

mycp:
    resource: "@mycpBundle/Resources/config/routing.yml"
    prefix:   /

mycp_own_details:
    pattern:  /{own_code}
    defaults: { _controller: frontEndBundle:ownership:own_details_direct }

mycp_frontend:
    resource: "@frontEndBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    type: be_simple_i18n

frontend_ckeck:
    pattern:  /user/check
frontend_login:
    pattern:  /{_locale}/login/
    defaults: { _controller: frontEndBundle:public:login }
frontend_logout:
    pattern: /user/logout

mycp_welcome_main:
    pattern:  /welcome/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: es }

mycp_main:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: es }

frontend_change_currency:
    pattern:  /change_currency/{curr_code}
    defaults: { _controller: frontEndBundle:currency:change_currency }


