# To catch all outdated routes of the old website the routing
# for website migration must be included first!
frontend_website_migration:
    resource: "@FrontEndBundle/Resources/config/routingFrontendWebsiteMigration.yml"

backend_login_check:
    pattern:  /backend/login_check
backend_login:
    pattern:  /backend/login/
    defaults: { _controller: mycpBundle:Public:login, urlLogin: 'backend_login_check'}
backend_logout:
    pattern: /backend/logout
casa_login_check:
    pattern:  /casa/login_check
casa_login:
    pattern:  /casa/login/
    defaults: { _controller: mycpBundle:Public:login, urlLogin: 'casa_login_check'}
casa_logout:
    pattern: /casa/logout

#lodging_login_check:
#    pattern:  /alojamiento/login_check
#lodging_login:
#    pattern:  /alojamiento/login/
#    defaults: { _controller: mycpBundle:Public:login, urlLogin: 'lodging_login_check' }
#lodging_logout:
#    pattern: /alojamiento/logout

mycp:
    resource: "@mycpBundle/Resources/config/routing.yml"
    prefix:   /

mycp_sitemap:
    path: /sitemap.{_format}
    defaults: { _controller: FrontEndBundle:Public:siteMap }

mycp_own_details:
    pattern:  /{own_code}/
    defaults: { _controller: FrontEndBundle:Ownership:ownDetailsDirect }

mycp_simple_details:
    pattern:  /simple/{mycp_code}/
    defaults: { _controller: FrontEndBundle:Ownership:simple }

mycp_frontend:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    type: be_simple_i18n

frontend_ckeck:
    pattern:  /user/check
frontend_login:
    pattern:  /{_locale}/login/
    defaults: { _controller: FrontEndBundle:Public:login }
frontend_logout:
    pattern: /user/logout

#mycp_welcome_main:
#    pattern:  /welcome/
#    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: en }

mycp_main:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_welcome, _locale: en }

remarketing_legal_terms:
    pattern:  /legal-terms-email/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_legal_terms
        permanent: true

remarketing_security_privacity:
    pattern:  /security-privacy-email/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_security_privacity
        permanent: true

remarketing_mycasatrip_available:
    pattern:  /mycasatrip-email/available/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_mycasatrip_available
        permanent: true

remarketing_details_ownership:
    pattern:  /accommodation-email/{own_name}/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_details_ownership
        permanent: true

remarketing_mycasatrip_cancel_offer:
    pattern:  /cancel-offer-email/{generalReservationId}/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_mycasatrip_cancel_offer
        permanent: true

remarketing_search_ownership:
    pattern:  /accommodations-email/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_search_ownership
        permanent: true

remarketing_check_availability_cart:
    pattern:  /check-cart-email/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_check_availability_cart
        permanent: true

remarketing_view_confirmation_reservation:
    pattern:  view-reservation-email/{id_booking}/{_locale}/{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_view_confirmation_reservation
        permanent: true

