security:
    encoders:
         MyCp\mycpBundle\Entity\user: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_for_backend:
            chain:
                providers: [backend, frontend]
        frontend:
            entity: { class: mycpBundle:user, property: user_email }
        backend:
            entity: { class: mycpBundle:user, property: user_name }
        #lodging:
        #    entity: { class: mycpBundle:user, property: user_name }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: ~

        backend:
            pattern:    ^/backend
            provider: chain_for_backend
            form_login:
                check_path: /backend/login_check
                login_path: /backend/login
                remember_me: true
                default_target_path: /backend/
                use_referer: false
            remember_me:
                key: '%secret%'
                #7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
                lifetime: 86400
                path: /
                domain: ~
            logout:
                path:   /backend/logout
                target: /backend/
                invalidate_session: false
                delete_cookies:
                    REMEMBERME: { path: ~, domain: ~}
            anonymous: ~
        modulo_casa:
            pattern:    ^/casa
            provider: chain_for_backend
            form_login:
                check_path: /casa/login_check
                login_path: /casa/login
                remember_me: true
                default_target_path: /casa
                use_referer: false
            remember_me:
                key: '%secret%'
                #7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
                lifetime: 86400
                path: /
                domain: ~
            logout:
                path:   /casa/logout
                target: /casa
                invalidate_session: false
                delete_cookies:
                    REMEMBERME: { path: ~, domain: ~}
            anonymous: ~
        modulo_casa_new:
            pattern:    ^/mycasa
            provider: chain_for_backend
            form_login:
                check_path: /mycasa/login_check
                login_path: /mycasa/login
                success_handler: authentication_handler
                failure_handler: authentication_handler
                remember_me: true
                default_target_path: /mycasa/dashboard
                use_referer: false
            remember_me:
                key: '%secret%'
                #7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
                lifetime: 86400
                path: /
                domain: ~
            logout:
                path:   /mycasa/logout
                target: /mycasa/dashboard
                invalidate_session: false
                delete_cookies:
                    REMEMBERME: { path: ~, domain: ~}
            anonymous: ~

        modulo_partner:
            pattern:  /partner/(.*)
            provider: chain_for_backend
            form_login:
                check_path: frontend_partner_login_check
                login_path: frontend_partner_login
                remember_me: true
                default_target_path: backend_partner_dashboard
                use_referer: false
            remember_me:
                key: '%secret%'
                #7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
                lifetime: 86400
                path: /
                domain: ~
            logout:
                path:   /partner/logout
                target: frontend_partner_home
                invalidate_session: false
                delete_cookies:
                    REMEMBERME: { path: ~, domain: ~}
            anonymous: ~


        #lodging:
        #    pattern:    ^/alojamiento
        #    provider: lodging
        #    form_login:
        #        check_path: /alojamiento/login_check
        #        login_path: /alojamiento/login
        #        remember_me: true
        #    remember_me:
        #        key: %secret%
        #        #7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
        #        lifetime: 86400
        #        always_remember_me: true
        #        path: /
        #        domain: ~
        #    logout:
        #        path:   /alojamiento/logout
        #        target: /alojamiento/
        #        invalidate_session: false
        #    anonymous: ~


        user:
            pattern:    ^/
            provider: frontend
            form_login:
                check_path: frontend_ckeck
                login_path: frontend_login
                remember_me: true
            remember_me:
                key: '%secret%'
                #7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
                lifetime: 86400
                path: /
                domain: ~
            logout:
                path:   /logout
                target: /
                invalidate_session: false
                delete_cookies:
                    REMEMBERME: { path: /, domain: ~}
            anonymous: ~

    access_control:
        - { path: /partner/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /partner/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /partner/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /partner/dashboard, role: IS_AUTHENTICATED_FULLY }

        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/olvido-contrasenna, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/cambiar-contrasenna, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/casa/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/casa/olvido-contrasenna, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/casa/cambiar-contrasenna, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mycasa/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mycasa/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mycasa/olvido-contrasenna, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mycasa/cambiar-contrasenna, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/mycp_cf, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, roles: IS_AUTHENTICATED_REMEMBERED}
#        - { path: ^/casa, roles: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/casa, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/mycasa, roles: IS_AUTHENTICATED_REMEMBERED}
       # - { path: ^/alojamiento/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/alojamiento/mycp_cf, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/alojamiento, roles: IS_AUTHENTICATED_REMEMBERED}
        #[ROLE_CLIENT_STAFF,ROLE_CLIENT_CASA,ROLE_CLIENT_CASA] }
        - { path: '^/[a-z]{2}/user/cart', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/confirmation', roles: [ROLE_CLIENT_TOURIST]}
        - { path: '^/[a-z]{2}/user/cart/add', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/cart/clear', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/remove', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/usuario/cesta', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/usuario/confirmacion', roles: [ROLE_CLIENT_TOURIST]}
        - { path: '^/[a-z]{2}/usuario/cesta/agregar', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/usuario/cesta/vaciar', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/usuario', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/payment', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/pago', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/zahlung', roles: [ROLE_CLIENT_TOURIST] }

        - { path: '^/[a-z]{2}/mycasatrip', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/perfil', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/profile', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/profil', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/user/change-password', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/usuario/cambiar-clave', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/benutzer/passwort-aendern', roles: [ROLE_CLIENT_TOURIST] }
