security:
    encoders:
         MyCp\mycpBundle\Entity\user: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        frontend:
            entity: { class: mycpBundle:user, property: user_email }
        backend:
            entity: { class: mycpBundle:user, property: user_name }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: ~

        backend:
            pattern:    ^/backend
            provider: backend
            form_login:
                check_path: /backend/login_check
                login_path: /backend/login
            remember_me:
                key: 7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
                lifetime: 86400
            logout:
                path:   /backend/logout
                target: /backend
            anonymous: ~

        user:
            pattern:    ^/
            provider: frontend
            form_login:
                check_path: frontend_ckeck
                login_path: frontend_login
            remember_me:
                key: 7dsa7ydasdy872187yegwhqeg9yw91hjsaa00
                lifetime: 86400
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/mycp_cf, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, roles: [ROLE_CLIENT_STAFF,ROLE_CLIENT_CASA,ROLE_CLIENT_CASA] }
        - { path: '^/[a-z]{2}/user/cart', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/confirmation', roles: [ROLE_CLIENT_TOURIST]}
        - { path: '^/[a-z]{2}/user/add', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/clear', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/remove', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/mycasatrip', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/perfil', roles: [ROLE_CLIENT_TOURIST] }
        - { path: '^/[a-z]{2}/profile', roles: [ROLE_CLIENT_TOURIST] }
