<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MyCp\mycpBundle\Entity\album;
use MyCp\mycpBundle\Entity\albumLang;
use MyCp\mycpBundle\Helpers\BackendModuleName;
use MyCp\mycpBundle\Helpers\DataBaseTables;
use MyCp\mycpBundle\Helpers\OrderByHelper;
use MyCp\mycpBundle\Helpers\OwnershipStatuses;

/**
 * accommodationCalendarFrequencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accommodationCalendarFrequencyRepository extends EntityRepository
{
    public function addFrequency($idAccommodation, $source = "Módulo Casa")
    {
        $em = $this->getEntityManager();
        $date = new \DateTime();

        $frequency = $em->getRepository("mycpBundle:accommodationCalendarFrequency")->findOneBy(array(
            "accommodation" => $idAccommodation,
            "updatedDate" => date("Y-m-d", $date->getTimestamp())
        ));

        if($frequency == null)
        {
            $accommodation = $em->getRepository("mycpBundle:ownership")->find($idAccommodation);

            $frequency = new accommodationCalendarFrequency();
            $frequency->setUpdatedDate($date)
                ->setAccommodation($accommodation)
                ->setSource($source);

            $em->persist($frequency);
            $em->flush();

            return true;
        }

        return false;
    }
}
