<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * destinationPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class albumPhotoRepository extends EntityRepository
{

    function getPhotosByIdAlbum($id_album)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT ap,app FROM mycpBundle:albumphoto ap JOIN ap.alb_pho_photo app
        WHERE ap.alb_pho_album= :id_album ORDER BY app.pho_order ASC");
        return $query->setParameter('id_album', $id_album)->getResult();
    }
}
