<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * albumCategoryLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class albumCategoryLangRepository extends EntityRepository
{

    function get_categories()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT cl,cat FROM mycpBundle:albumcategorylang cl
        JOIN cl.album_cat_id_cat cat
        GROUP BY cl.album_cat_id_cat");
        return $query->getArrayResult();
    }
}
