<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clientCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientCommentRepository extends EntityRepository
{

    /**
     * Create a comment of a client
     * @param user $client
     * @param user $staffMember
     * @param $commentText
     */
    public function insert(user $client, user $staffMember, $commentText)
    {
        $em = $this->getEntityManager();

        $comment = new clientComment();
        $comment->setCommentClientUser($client);
        $comment->setCommentStaffUser($staffMember);
        $comment->setCommentText($commentText);

        $em->persist($comment);
        $em->flush();
    }
}
