<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * faqCategoryLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faqCategoryLangRepository extends EntityRepository
{
    function get_categories()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT cl,cat FROM mycpBundle:faqcategorylang cl
        JOIN cl.faq_cat_id_cat cat
        GROUP BY cl.faq_cat_id_cat");
        return $query->getArrayResult();
    }
}

