<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * permissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class favoriteRepository extends EntityRepository {

    public function insert($data) {
        $em = $this->getEntityManager();
        $ownership = null;
        $user = null;
        $destination = null;
        if ($data['favorite_ownership_id'] != null)
            $ownership = $em->getRepository('mycpBundle:ownership')->find($data['favorite_ownership_id']);

        if ($data['favorite_user_id'] != null)
            $user = $em->getRepository('mycpBundle:user')->find($data['favorite_user_id']);

        if ($data['favorite_destination_id'] != null)
            $destination = $em->getRepository('mycpBundle:destination')->find($data['favorite_destination_id']);

        $is_ownership = $data['favorite_ownership_id'] != null;
        $element_id = ($is_ownership) ? $data['favorite_ownership_id'] : $data['favorite_destination_id'];
        if (!$this->is_in_favorite($element_id,$is_ownership,$data['favorite_user_id'],$data['favorite_session_id'])) {
            $favorite = new favorite();
            $favorite->setFavoriteCreationDate(new \DateTime());
            $favorite->setFavoriteOwnership($ownership);
            $favorite->setFavoriteDestination($destination);
            $favorite->setFavoriteSessionId($data['favorite_session_id']);
            $favorite->setFavoriteUser($user);

            $em->persist($favorite);
            $em->flush();
        }
    }

    public function delete($data) {
        $em = $this->getEntityManager();
        $query_string = "DELETE mycpBundle:favorite f ";
        $where = "";

        if ($data['favorite_ownership_id'] != null)
            $where .= (($where == "") ? " WHERE " : " AND ") . " f.favorite_ownership =" . $data['favorite_ownership_id'];
        else if ($data['favorite_destination_id'] != null)
            $where .= (($where == "") ? " WHERE " : " AND ") . " f.favorite_destination =" . $data['favorite_destination_id'];

        if ($data['favorite_session_id'] != null)
            $where .= (($where == "") ? " WHERE " : " AND ") . " f.favorite_session_id ='" . $data['favorite_session_id'] . "'";
        else if ($data['favorite_user_id'] != null)
            $where .= (($where == "") ? " WHERE " : " AND ") . " f.favorite_user =" . $data['favorite_user_id'];

        $query = $em->createQuery($query_string . $where);
        $query->execute();
    }

    public function get_total($user_id = null, $session_id = null) {
        $em = $this->getEntityManager();
        $query_string = "SELECT f FROM mycpBundle:favorite f";

        if ($user_id != null)
            $query_string.= " WHERE f.favorite_user = $user_id";
        else if ($session_id != null)
            $query_string .= " WHERE f.favorite_session_id = '$session_id'";

        return count($em->createQuery($query_string)->getResult());
    }

    public function is_in_favorite($element_id, $is_ownership = true, $user_id = null, $session_id = null) {
        $em = $this->getEntityManager();
        $query_string = "SELECT f FROM mycpBundle:favorite f";

        if ($user_id != null)
            $query_string.= " WHERE f.favorite_user = $user_id";
        else if ($session_id != null)
            $query_string .= " WHERE f.favorite_session_id = '$session_id'";

        $query_string .= ($is_ownership) ? " AND f.favorite_ownership = $element_id" : " AND f.favorite_destination = $element_id";
        return count($em->createQuery($query_string)->getResult()) > 0;
    }

    public function is_in_favorite_array($array_elements, $is_ownership = true, $user_id = null, $session_id = null) {
        if (is_array($array_elements)) {
            $results = array();
            foreach ($array_elements as $element) {
                if ($element != null) {
                    $id = ($is_ownership) ? $element->getOwnId() : $element->getDesId();
                    $results[$id] = $this->is_in_favorite($id, $is_ownership, $user_id, $session_id);
                }
            }
            return $results;
        }
        return null;
    }
    
    public function get_list($is_ownership = true, $user_id = null, $session_id = null) {
        $em = $this->getEntityManager();
        $query_string = "SELECT f FROM mycpBundle:favorite f";

        if ($user_id != null)
            $query_string.= " WHERE f.favorite_user = $user_id";
        else if ($session_id != null)
            $query_string .= " WHERE f.favorite_session_id = '$session_id'";

        $query_string .= ($is_ownership) ? " AND f.favorite_ownership IS NOT NULL " : " AND f.favorite_destination IS NOT NULL ";

        return $em->createQuery($query_string)->getResult();        
    }

    public function get_element_id_list($is_ownership = true, $user_id = null, $session_id = null) {
        $em = $this->getEntityManager();
        $query_string = "SELECT f FROM mycpBundle:favorite f";

        if ($user_id != null)
            $query_string.= " WHERE f.favorite_user = $user_id";
        else if ($session_id != null)
            $query_string .= " WHERE f.favorite_session_id = '$session_id'";

        $query_string .= ($is_ownership) ? " AND f.favorite_ownership IS NOT NULL " : " AND f.favorite_destination IS NOT NULL ";

        $favorites = $em->createQuery($query_string)->getResult();
        $results = "0";
        foreach ($favorites as $favorite) {
            $results .= "," . (($is_ownership) ? $favorite->getFavoriteOwnership()->getOwnId() : $favorite->getFavoriteDestination()->getDesId());
        }
        
        return $results;
    }

    public function user_ids($controller) {
        $user_id = null;
        $session_id = null;
        $user = $controller->get('security.context')->getToken()->getUser();

        if ($user != null && $user != "anon.")
            $user_id = $user->getUserId();

        if ($user_id == null) {
            if (isset($_COOKIE["mycp_user_session"]))
                $session_id = $_COOKIE["mycp_user_session"];
            else {
                $session = $controller->getRequest()->getSession();
                $now = time();
                $session_id = $session->getId(); //."_".$now;
                setcookie("mycp_user_session", $session_id, time() + 60 * 60 * 24 * 365);
            }
        }

        return array('user_id' => $user_id, 'session_id' => $session_id);
    }

}
