<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * logRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logRepository extends EntityRepository
{

    function get_logs($post)
    {
        $user=$post['user'];
        $module=$post['module'];
        $from_date=$post['from_date'];
        $to_date=$post['to_date'];

        $string0='';
        if($user!='')
            $string0="lu.user_id='$user'";

        $string1='';
        if($module!='')
        {
            $string1_1='';
            if($user!='')
                $string1_1='AND';
            $string1="$string1_1 l.log_module='$module'";
        }


        $string2='';
        if($from_date!='')
        {
            $string2_1='';
            if($user!='' or $module!='')
                $string2_1='AND';
            $array_date_from=explode('/',$from_date);
            $string2=$array_date_from[2].'-'.$array_date_from[1].'-'.$array_date_from[0];
            $string2="$string2_1 l.log_date >='$string2'";
        }
        $string3='';
        if($to_date!='')
        {
            $string3_1='';
            if($user!='' or $module!='' or $from_date!='')
                $string3_1='AND';
            $array_date_from=explode('/',$to_date);
            $string3=$array_date_from[2].'-'.$array_date_from[1].'-'.$array_date_from[0];
            $string3="$string3_1 l.log_date <='$string3'";
        }

        $where='WHERE';
        if($user=='' && $module=='' && $from_date=='' && $to_date=='')
            $where='';


        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT l,lu FROM mycpBundle:log l
        JOIN l.log_user lu
        $where $string0 $string1 $string2 $string3");
        return $query->getResult();
    }

}
