<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MyCp\mycpBundle\Entity\ownershipStatus;

/**
 * provinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class provinceRepository extends EntityRepository
{
    function getProvincesForAutocomplete($prov_part_name)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery("SELECT p FROM mycpBundle:province p
        WHERE p.prov_name LIKE '%$prov_part_name%' ORDER BY p.prov_name ASC");
        return $query->getResult();
    }

    function getProvinces()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery("SELECT p FROM mycpBundle:province p
        ORDER BY p.prov_name ASC");
        return $query->getResult();
    }

    function getMainMenu()
    {
        $em = $this->getEntityManager();
        $query_string = "SELECT DISTINCT p.prov_id, p.prov_name,
                        (SELECT count(o) FROM mycpBundle:ownership o where o.own_address_province = p.prov_id AND o.own_status = ".ownershipStatus::STATUS_ACTIVE.") as total_owns
                         FROM mycpBundle:province p
                         ORDER BY total_owns DESC
                         ";
        return $em->createQuery($query_string)->getResult();
    }
}
