<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * provinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class provinceRepository extends EntityRepository
{
    /**
     * Yanet - Inicio
     */
    function getProvincesForAutocomplete($prov_part_name)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery("SELECT p FROM mycpBundle:province p
        WHERE p.prov_name LIKE '%$prov_part_name%' ORDER BY p.prov_name ASC");
        return $query->getResult();
    }
    
    function getProvinces()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery("SELECT p FROM mycpBundle:province p
        ORDER BY p.prov_name ASC");
        return $query->getResult();
    }


    /**
     * Yanet - Fin
     */
}
