<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roleRepository extends EntityRepository
{
    function getStaffRoles() {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT r FROM mycpBundle:role r
        WHERE r.role_name LIKE 'ROLE_CLIENT_STAFF%'");
        return $query->getResult();
    }
}
