<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * rolePermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rolePermissionRepository extends EntityRepository
{
    function getByRole($id_role)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT rp,per FROM mycpBundle:rolePermission rp JOIN rp.rp_permission per
        WHERE rp.rp_role= :id_role
        ORDER BY per.perm_category ASC");
        return $query->setParameter("id_role", $id_role)->getResult();
    }
}
