<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MyCp\mycpBundle\Helpers\SyncStatuses;

/**
 * roomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roomRepository extends EntityRepository {

    public function getNotSynchronized() {
        $em = $this->getEntityManager();
        $query_string = "SELECT o
                        FROM mycpBundle:room o
                        WHERE o.room_sync_st<>" . SyncStatuses::SYNC;

        return $em->createQuery($query_string)->getResult();
    }

    public function getReservationsForCalendar($roomId)
    {
        $em = $this->getEntityManager();
        $query_string = "SELECT o
                        FROM mycpBundle:ownershipReservation o
                        WHERE o.own_res_selected_room_id = :roomId
                          AND (o.own_res_status = :statusReserved)
                          AND (o.own_res_reservation_from_date >= :dateFrom OR (o.own_res_reservation_from_date < :dateFrom AND o.own_res_reservation_to_date >= :dateFrom))
                        ORDER BY o.own_res_reservation_from_date DESC";

        $dateFrom = date("Y")."-01-01";

        return $em->createQuery($query_string)
                ->setParameter('roomId', $roomId)
                ->setParameter('statusReserved', ownershipReservation::STATUS_RESERVED)
                ->setParameter('dateFrom', $dateFrom)
                ->setParameter('roomId', $roomId)
                ->getResult();
    }

}
