<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * touristFailureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class touristFailureRepository extends EntityRepository {

    public function findByAccommodation($accommodationId){
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->from("mycpBundle:touristFailure", "p")
            ->select("p")
            ->join("p.accommodation", "accommodation")
            ->where("accommodation.own_id = :accommodationId")
            ->setParameter("accommodationId", $accommodationId)
            ->orderBy("p.creationDate", "DESC")
            ->getQuery();
        ;
        return $query;
    }

}
