<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * userCasaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userCasaRepository extends EntityRepository
{
    function get_users_casa()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT uc FROM mycpBundle:userCasa uc
        GROUP BY uc.user_casa_user");
        return $query->getResult();
    }
}
