<?php

namespace MyCp\mycpBundle\Entity;

/**
 * userStaffManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userStaffManagerRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveUserStaffManager($userStaffManager) {
        $em = $this->getEntityManager();
        $em->persist($userStaffManager);
        $em->flush();
    }

    public function removeUserStaffManager($userStaffManager) {
        $em = $this->getEntityManager();
        $em->remove($userStaffManager);
        $em->flush();
    }

    public function insertUserDestination($userStaffManager, $destination){
        $em = $this->getEntityManager();
        $conn = $em->getConnection();
        $destination*=1;

        //comprobar que no exista una tupla con $userStaffManager, $destination;
        $query = "SELECT userstaffmanager_destination.user_staff_manager FROM userstaffmanager_destination
WHERE userstaffmanager_destination.user_staff_manager = :user_staff_manager AND userstaffmanager_destination.destination = :destination";
        $stmt = $conn->prepare($query);
        $stmt->bindValue('user_staff_manager', $userStaffManager);
        $stmt->bindValue('destination', $destination);
        $stmt->execute();
        $res = $stmt->fetchAll();

        if(count($res) == 0){
            $query = "INSERT INTO userstaffmanager_destination(user_staff_manager, destination) VALUE (:user_staff_manager, :destination)";
            $stmt = $conn->prepare($query);
            $stmt->bindValue('user_staff_manager', $userStaffManager);
            $stmt->bindValue('destination', $destination);
            $stmt->execute();
        }
    }

    public function clearUserDestination($userStaffManager){
        $em = $this->getEntityManager();
        $conn = $em->getConnection();

        $query = "DELETE FROM userstaffmanager_destination WHERE user_staff_manager = :user_staff_manager";
        $stmt = $conn->prepare($query);
        $stmt->bindValue('user_staff_manager', $userStaffManager);
        $stmt->execute();
    }
}
