<?php

namespace MyCp\mycpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * userCasaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userCasaRepository extends EntityRepository
{
    function get_users_casa()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT uc FROM mycpBundle:userCasa uc
        GROUP BY uc.user_casa_user");
        return $query->getResult();
    }

    function get_user_casa_by_user_id($user_id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT uc FROM mycpBundle:userCasa uc join uc.user_casa_user us
        Where us.user_id = :user_id");
        $query->setParameter(':user_id', $user_id);
        return $query->getSingleResult();
    }
    
    function get_owners_photos($ownership_id)
    {
        $em = $this->getEntityManager();
        $query_string = "SELECT pho.pho_name as photo
                  FROM mycpBundle:userCasa uc
                  JOIN uc.user_casa_user u
                  JOIN u.user_photo pho
                  WHERE uc.user_casa_ownership = $ownership_id";
        
        $query = $em->createQuery($query_string);
        $photo_name = $query->setMaxResults(1)->getResult();
        
        if ($photo_name == null)
                $photo_name = "no_photo.gif";
            else if (!file_exists(realpath("uploads/userImages/" . $photo_name))) 
                $photo_name = "no_photo.gif";
        return $photo_name;
    }


}
