frontend_mycasatrip_home:
    pattern:  /
    defaults: { _controller: FrontEndBundle:Mycasatrip:home }

frontend_mycasatrip_pending:
    locales:  { en: "/pending/{order_by}", es: "/pendientes/{order_by}", de: "/ausstehend/{order_by}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:pending ,order_by:0}

frontend_mycasatrip_available:
    locales:  { en: "/available/{order_by}", es: "/disponibles/{order_by}",de: "/verfuegbar/{order_by}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:available,order_by:0 }

frontend_mycasatrip_reserve:
    locales:  { en: "/reserved/{order_by}", es: "/reservadas/{order_by}",de: "/reserviert/{order_by}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:reserve,order_by:0 }

frontend_mycasatrip_historial_reserve:
    locales:  { en: "/booking-history/{order_by}", es: "/historial-reservas/{order_by}",de: "/buchungsverlauf/{order_by}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:historyReserve,order_by:0 }

frontend_mycasatrip_payment:
    locales:  { en: "/payment-confirmed/{order_by}", es: "/confirmadas-pago/{order_by}", de: "/zahlung-bestaetigt/{order_by}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:payments,order_by:0 }

frontend_mycasatrip_historial_consult:
    locales:  { en: "/inquired-history/{order_by}", es: "/historial-consultadas/{order_by}",de: "/anfragenverlauf/{order_by}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:historyConsult,order_by:0 }

frontend_mycasatrip_favorites_destinations:
    locales:  { en: "/favorites/destinations", es: "/favoritos/destinos",de: "/favoriten/reiseziele" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:favoritesDestinations }

frontend_mycasatrip_favorites_accomodations:
    locales:  { en: "/favorites/accomodations", es: "/favoritos/alojamientos", de: "/favoriten/unterkuenfte" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:favoritesAccomodations }

frontend_mycasatrip_comments:
    locales:  { en: "/comments/{comment_type}", es: "/comentarios/{comment_type}",de: "/bewertungen/{comment_type}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:comments }

frontend_mycasatrip_cancel_offer:
    locales:  { en: "/cancel-offer/{generalReservationId}", es: "/cancelar-oferta/{generalReservationId}",de: "/offerte-annullieren/{generalReservationId}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:cancelOffer }

frontend_cancel_offer_callback:
    locales:  { en: "/cancel-offer-callback/{genResID}", es: "/cancelar-oferta-callback/{genResID}",de: "/offerte-annullieren-callback/{genResID}" }
    defaults: { _controller: FrontEndBundle:Mycasatrip:cancelOfferCallback }

frontend_mycasatrip_cancel_offer_remarketing:
    locales:  { en: "cancel-offer-email/{generalReservationId}", es: "cancelar-oferta-correo/{generalReservationId}",de: "offerte-annullieren-email/{generalReservationId}" }
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_mycasatrip_cancel_offer
        permanent: true
