frontend_list_faq:
    locales:  { en: "/faqs/", es: "/preguntas_frecuentes/" }
    defaults: { _controller: frontEndBundle:faq:list }
    
frontend_filter_faq:
    pattern:  /filter_faqs/
    defaults: { _controller: frontEndBundle:faq:filter }
