frontend_mycasatrip_home:
    pattern:  /
    defaults: { _controller: frontEndBundle:mycasatrip:home }

frontend_mycasatrip_pending:
    pattern:  /pending
    defaults: { _controller: frontEndBundle:mycasatrip:reservations_pending }

frontend_mycasatrip_available:
    pattern:  /available
    defaults: { _controller: frontEndBundle:mycasatrip:reservations_available }

frontend_mycasatrip_review:
    pattern:  /review/{id_reservation}/
    defaults: { _controller: frontEndBundle:mycasatrip:reservation_review }

