frontend_redirect_reservation_reservation:
    locales:  { en: "/user/reservation/redirect/", es: "/usuario/reservacion/redireccionar/", de: "/user/reservation/redirect/" }
    defaults: { _controller: FrontEndBundle:Reservation:redirectReservation }

frontend_reservation_reservation:
    locales:  { en: "/user/reservation/", es: "/usuario/reservacion/", de: "/user/reservation/" }
    defaults: { _controller: FrontEndBundle:Reservation:reservation }

frontend_confirmation_reservation:
    locales:  { en: "/user/payment/{id_booking}/", es: "/usuario/pago/{id_booking}/", de: "/user/payment/{id_booking}/" }
    defaults: { _controller: FrontEndBundle:Reservation:confirmation }

frontend_view_confirmation_reservation:
    locales:  { en: "/user/reservation/view/{id_booking}/", es: "/usuario/reservacion/detalles/{id_booking}/", de: "/user/reservation/view/{id_booking}/" }
    defaults: { _controller: FrontEndBundle:Reservation:viewConfirmation }

frontend_boucher_reservation:
    locales:  { en: "/user/confirmation/{id_booking}/", es: "/usuario/confirmacion/{id_booking}/", de: "/user/confirmation/{id_booking}/" }
    defaults: { _controller: FrontEndBundle:Reservation:generatePdfVoucher }




