frontend_mycasatrip_home:
    pattern:  /
    defaults: { _controller: frontEndBundle:mycasatrip:home }

frontend_mycasatrip_pending:
    locales:  { en: "/pending/{order_by}", es: "/pendientes/{order_by}", de: "/ausstehend/{order_by}" }
    defaults: { _controller: frontEndBundle:mycasatrip:reservations_pending ,order_by:0}

frontend_mycasatrip_available:
    locales:  { en: "/available/{order_by}", es: "/disponibles/{order_by}",de: "/verfuegbar/{order_by}" }
    defaults: { _controller: frontEndBundle:mycasatrip:reservations_available,order_by:0 }

frontend_mycasatrip_reserve:
    locales:  { en: "/reserved/{order_by}", es: "/reservadas/{order_by}",de: "/reserviert/{order_by}" }
    defaults: { _controller: frontEndBundle:mycasatrip:reservations_reserve,order_by:0 }

frontend_mycasatrip_historial_reserve:
    locales:  { en: "/booking_history/{order_by}", es: "/historial_reservas/{order_by}",de: "/buchungsverlauf/{order_by}" }
    defaults: { _controller: frontEndBundle:mycasatrip:history_reservations_reserve,order_by:0 }

frontend_mycasatrip_payment:
    locales:  { en: "/payment_confirmed/{order_by}", es: "/confirmadas_pago/{order_by}", de: "/zahlung_bestaetigt/{order_by}" }
    defaults: { _controller: frontEndBundle:mycasatrip:reservations_payment,order_by:0 }

frontend_mycasatrip_historial_consult:
    locales:  { en: "/inquired_history/{order_by}", es: "/historial_consultadas/{order_by}",de: "/anfragenverlauf/{order_by}" }
    defaults: { _controller: frontEndBundle:mycasatrip:history_reservation_consult,order_by:0 }

frontend_mycasatrip_favorites_destinations:
    locales:  { en: "/favorites/destinations", es: "/favoritos/destinos",de: "/favoriten/reiseziele" }
    defaults: { _controller: frontEndBundle:mycasatrip:favorites_destinations }
    
frontend_mycasatrip_favorites_accomodations:
    locales:  { en: "/favorites/accomodations", es: "/favoritos/alojamientos", de: "/favoriten/unterkuenfte" }
    defaults: { _controller: frontEndBundle:mycasatrip:favorites_accomodations }
    
frontend_mycasatrip_comments:
    locales:  { en: "/comments/{comment_type}", es: "/comentarios/{comment_type}",de: "/bewertungen/{comment_type}" }
    defaults: { _controller: frontEndBundle:mycasatrip:comments }
    
frontend_mycasatrip_update_favorites_statistics_callback:
    locales:  { en: "/update_favorites_statistics_callback/", es: "/actualizar_estadisticas_favoritos_callback/", de:"rontend_mycasatrip_update_favorites_statistics_callback" }
    defaults: { _controller: frontEndBundle:mycasatrip:update_favorites_statistics_callback }



