frontend_list_destinations:
    locales:  { en: "/destinations/", es: "/destinos/", de: "/reiseziele/", fr: "/destinations/", it: "/destinazioni/" }
    defaults: { _controller: FrontEndBundle:Destination:popularList }

frontend_filter_by_municipality_destinations:
    locales:  { en: "/destinations/{province_id}/{municipality_id}", es: "/destinos/{province_id}/{municipality_id}", de: "/reiseziele/{province_id}/{municipality_id}", fr: "/destinations/{province_id}/{municipality_id}", it: "/destinazioni/{province_id}/{municipality_id}" }
    defaults: { _controller: FrontEndBundle:Destination:popularList }

frontend_filter_by_province_destinations:
    locales:  { en: "/destinations-province/{province_id}", es: "/destinos-provincia/{province_id}", de: "/reiseziele-provinz/{province_id}" , fr: "/destinations-provinz/{province_id}", it: "/destinazioni-provinz/{province_id}" }
    defaults: { _controller: FrontEndBundle:Destination:popularList }

frontend_details_destination:
    locales:  { en: "/destinations/{destination_name}", es: "/destinos/{destination_name}", de: "/reiseziele/{destination_name}", fr: "/destinations/{destination_name}", it: "/destinazioni/{destination_name}" }
    defaults: { _controller: FrontEndBundle:Destination:details }

frontend_filter_destination:
    locales:  { en: "/filter-destinations/", es: "/filtrar-destinos/", de: "/filter-destinations/", fr: "/filter-destinations/", it: "/filter-destinations/" }
    defaults: { _controller: FrontEndBundle:Destination:filter }

frontend_nearby_destination:
    locales:  { en: "/owns-nearby/{destination_name}/{destination_id}", es: "/alojamientos-cercanos/{destination_name}/{destination_id}", de: "/owns-nearby/{destination_name}/{destination_id}", fr: "/owns-nearby/{destination_name}/{destination_id}", it: "/owns-nearby/{destination_name}/{destination_id}" }
    defaults: { _controller: FrontEndBundle:Destination:ownsNearbyCallback }

frontend_change_view_destination_callback:
    locales:  { en: "/change-results-view/{destination_name}/{destination_id}", es: "/cambiar-vista-resultados/{destination_name}/{destination_id}", de: "/change-results-view/{destination_name}/{destination_id}", fr: "/change-results-view/{destination_name}/{destination_id}", it: "/change-results-view/{destination_name}/{destination_id}" }
    defaults: { _controller: FrontEndBundle:Destination:searchChangeViewResults }

frontend_byprovince_destination_callback:
    locales:  { en: "/byprovince", es: "/porprovincia", de: "/byprovince", fr: "/byprovince", it: "/byprovince" }
    defaults: { _controller: FrontEndBundle:Destination:byProvince }

frontend_activities_destination_callback:
    locales:  { en: "/activities_destination", es: "/activities_destination", de: "/activities_destination", fr: "/activities_destination", it: "/activities_destination" }
    defaults: { _controller: FrontEndBundle:Destination:getDestinationsByActivitiesForMap }
