frontend_payment_poll_payment:
    pattern:  /payment/poll_payment/{reservationId}
    defaults: { _controller: frontEndBundle:payment:pollPayment, reservationId: 0 }

frontend_payment_skrill:
    pattern:  /payment/skrill_payment/{reservationId}
    defaults: { _controller: frontEndBundle:payment:skrillPayment, reservationId: 0}

frontend_payment_skrill_return:
    pattern:  /payment/skrill_return/{reservationId}
    defaults: { _controller: frontEndBundle:payment:skrillReturn, reservationId: 0}

frontend_payment_skrill_cancel:
    pattern:  /payment/skrill_cancel
    defaults: { _controller: frontEndBundle:payment:skrillCancel }

frontend_payment_skrill_status:
    pattern:  /payment/skrill_status
    defaults: { _controller: frontEndBundle:payment:skrillStatus }

frontend_payment_skrill_test_response:
    pattern:  /payment/skrill_test_response/{status}
    defaults: { _controller: frontEndBundle:payment:skrillTestResponse, status: 'no status' }

frontend_payment_skrill_test_status:
    pattern:  /payment/skrill_test_status/{reservationId}/{status}
    defaults: { _controller: frontEndBundle:payment:skrillSendTestPostRequest, reservationId: 0, status: 0 }

