frontend_get_reservation_calendar_ownership_callback:
    pattern:  /reservation-calendar/
    defaults: { _controller: frontEndBundle:ownership:get_reservation_calendar }

frontend_details_ownership:
    locales:  { en: "/accommodation/{own_name}", es: "/alojamiento/{own_name}", de: "/unterkunft/{own_name}" }
    defaults: { _controller: frontEndBundle:ownership:details }

frontend_last_added_ownership:
    locales:  { en: "/last-added-accommodation/", es: "/ultimos-alojamientos-agregados/", de: "/zuletzt-hinzugefuegte-unterkuenfte/" }
    defaults: { _controller: frontEndBundle:ownership:last_added_list }

frontend_category_ownership:
    locales:  { en: "/accommodations-by-category/{category}", es: "/alojamientos-por-categoria/{category}", de: "/unterkuenfte-nach-kategorie/{category}" }
    defaults: { _controller: frontEndBundle:ownership:category }

frontend_search_ownership:
    locales:  { en: "/accommodations/{text}/{arrival}/{departure}/{guests}/{rooms}", es: "/alojamientos/{text}/{arrival}/{departure}/{guests}/{rooms}", de: "/unterkuenfte/{text}/{arrival}/{departure}/{guests}/{rooms}" }
    defaults: { _controller: frontEndBundle:ownership:search,text:'null',arrival:'null',departure:'null',guests:1,rooms:1 }

frontend_order_search_results_ownership_callback:
    pattern:  /order-results/
    defaults: { _controller: frontEndBundle:ownership:search_order_results }

frontend_change_view_ownership_callback:
    pattern:  /change-results-view/
    defaults: { _controller: frontEndBundle:ownership:search_change_view_results }

frontend_research_ownership_callback:
  pattern: /research/
  defaults: {_controller: frontEndBundle:ownership:research }
  requirements:
        _method:  GET|POST

frontend_filter_ownership_callback:
    pattern:  /filter/
    defaults: { _controller: frontEndBundle:ownership:filter }

frontend_filter_statistics_ownership_callback:
    pattern:  /filter-statistics/
    defaults: { _controller: frontEndBundle:ownership:get_filters_statistics }

frontend_map_markers_ownership_callback:
    pattern:  /map-markers/
    defaults: { _controller: frontEndBundle:ownership:map_markers_list }

frontend_update_rating_ownership:
    pattern:  /update-rating/{ownid}
    defaults: { _controller: frontEndBundle:ownership:update_rating }

frontend_map_details_ownership_callback:
    pattern:  /map-details-ownership/{ownGeolocateX}/{ownGeolocateY}/{ownName}/{description}/{image}
    defaults: { _controller: frontEndBundle:ownership:map_details_ownership }
    
frontend_map_resized_ownership_callback:
    pattern:  /map-resized/{in_searcher}/{destination_name}
    defaults: { _controller: frontEndBundle:ownership:map_resized }
    
frontend_voted_best_list_ownership:
    locales:  { en: "/top-rated-accommodations/", es: "/alojamientos-mejores-votados/", de: "/top-unterkuenfte/" }
    defaults: { _controller: frontEndBundle:ownership:voted_best_list }

frontend_type_list_ownership:
    locales:  { en: "/accommodations_by_type/{type}", es: "/alojamientos_por_tipo/{type}", de: "/unterkuenfte_nach_typ/{type}" }
    defaults: { _controller: frontEndBundle:ownership:type_list }
    
frontend_top_rated_callback_ownership:
    pattern:  /top-rated-callback/
    defaults: { _controller: frontEndBundle:ownership:top_rated_callback }
    
frontend_top_rated_change_category_callback_ownership:
    pattern:  /top-rated-change-category-callback/
    defaults: { _controller: frontEndBundle:ownership:top_rated_change_category_callback }
