frontend_review_reservation:
    pattern:  /review/{id_ownership}/{data}
    defaults: { _controller: frontEndBundle:reservation:review }

frontend_review_redirect_reservation:
    pattern:  /review_redirect/{id_ownership}/
    defaults: { _controller: frontEndBundle:reservation:review_redirect }
    requirements:
        _method:  POST

frontend_confirm_redirect_reservation:
    pattern:  /confirm_redirect/{id_ownership}/
    defaults: { _controller: frontEndBundle:reservation:confirm_redirect }
    requirements:
        _method:  POST

frontend_review_confirm_reservation:
    pattern:  /check/{id_ownership}/{data}
    defaults: { _controller: frontEndBundle:reservation:review_confirm }
