frontend_insert_comment:
    locales:  { en: "/insert-comment/{ownid}", es: "/insertar-commentario/{ownid}", de: "/insert-comment/{ownid}" }
    defaults: { _controller: FrontEndBundle:Comment:insert }
