frontend_view_cart:
    locales:  { en: "user/cart/", es: "usuario/cesta/", de: "user/cart/" }
    defaults: { _controller: FrontEndBundle:Cart:viewCart }

frontend_add_to_cart:
    locales:  { en: "user/cart/add/{id_ownership}", es: "usuario/cesta/agregar/{id_ownership}", de: "user/cart/add/{id_ownership}" }
    defaults: { _controller: FrontEndBundle:Cart:addToCart }

frontend_remove_from_cart_callback:
    pattern:  /user/cart/remove/{data}
    defaults: { _controller: FrontEndBundle:Cart:removeFromCart }

frontend_empty_cart:
    locales:  { en: "user/cart/clear/", es: "usuario/cesta/vaciar/", de: "benutzer/einkaufs-reservierungen/leer/" }
    defaults: { _controller: FrontEndBundle:Cart:emptyCart }

