frontend_about_us:
    locales:  { en: "/who-we-are/", es: "/quienes-somos/",de: "/wer-wir-sind/" }
    defaults: { _controller: FrontEndBundle:Information:aboutUs }

frontend_legal_terms:
    locales:  { en: "/legal-terms/", es: "/terminos-legales/",de: "/allgemeine-geschaeftsbedingungen/" }
    defaults: { _controller: FrontEndBundle:Information:legalTerms }

frontend_security_privacity:
    locales:  { en: "/security-privacy/", es: "/seguridad-privacidad/",de: "/datenschutz/" }
    defaults: { _controller: FrontEndBundle:Information:securityPrivacity }

frontend_sitemap_information:
    locales:  { en: "/sitemap/", es: "/mapa-del-sitio/", de: "/sitemap/" }
    defaults: { _controller: FrontEndBundle:Information:sitemap }

frontend_how_it_works_information:
    locales:  { en: "/how-it-works/", es: "/como-funciona/", de: "/so-funktioniert-es/" }
    defaults: { _controller: FrontEndBundle:Information:howItWorks }

frontend_legal_terms_remarketing:
    locales:  { en: "legal-terms-email/", es: "terminos-legales-correo/",de: "allgemeine-geschaeftsbedingungen-email/" }
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_legal_terms
        permanent: true

frontend_security_privacity_remarketing:
    locales:  { en: "security-privacy-email/", es: "seguridad-privacidad-correo/",de: "datenschutz-email/" }
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_security_privacity
        permanent: true
