frontend_list_information:
    pattern:  /information/{information_type}
    defaults: { _controller: frontEndBundle:information:list }
    
frontend_sitemap_information:
    pattern:  /sitemap/
    defaults: { _controller: frontEndBundle:information:sitemap }
    
frontend_how_it_works_information:
    pattern:  /how_it_works/
    defaults: { _controller: frontEndBundle:information:how_it_works }
