frontend_about_us:
    locales:  { en: "/about-us/", es: "/sobre-nosotros/",de: "/uber-uns/" }
    defaults: { _controller: FrontEndBundle:Information:aboutUs }

frontend_legal_terms:
    locales:  { en: "/terms/", es: "/terminos/",de: "/nutzungsbedingungen/" }
    defaults: { _controller: FrontEndBundle:Information:legalTerms }

frontend_security_privacity:
    locales:  { en: "/security-privacy/", es: "/seguridad-privacidad/",de: "/datenschutz/" }
    defaults: { _controller: FrontEndBundle:Information:securityPrivacity }

frontend_sitemap_information:
    locales:  { en: "/sitemap/", es: "/mapa-del-sitio/", de: "/sitemap/" }
    defaults: { _controller: FrontEndBundle:Information:sitemap }

frontend_how_it_works_information:
    locales:  { en: "/how-it-works/", es: "/como-funciona/", de: "/so-funktioniert-es/" }
    defaults: { _controller: FrontEndBundle:Information:howItWorks }


