frontend_register_user:
    locales:  { en: "/user_registrate/", es: "/registrar_usuario/", de: "/benutzer_login/" }
    defaults: { _controller: frontEndBundle:user:register }

frontend_enable_user:
    locales:  { en: "/activate_user/{string}", es: "/activar_usuario/{string}", de: "/benutzer_aktivieren/{string}"  }
    defaults: { _controller: frontEndBundle:user:enable }

frontend_restore_password_user:
    locales:  { en: "/restore_password/", es: "/restaurar_clave/", de: "/passwort_wiederherstellen/" }
    defaults: { _controller: frontEndBundle:user:restore_password }

frontend_change_password_user:
    locales:  { en: "/change_password/{string}", es: "/cambiar_clave/{string}", de: "/passwort_aendern/{string}" }
    defaults: { _controller: frontEndBundle:user:change_password }

frontend_register_confirmation_user:
    pattern:  /register_confirmation/
    locales:  { en: "/confirmation_of_registration/", es: "/confirmacion_de_registro/", de: "/anmeldungsbestaetigung/" }
    defaults: { _controller: frontEndBundle:user:register_user_confirmation }
    
frontend_contact_user:
    locales:  { en: "/contact/", es: "/contacto/", de: "/kontakt/" }
    defaults: { _controller: frontEndBundle:user:contact }
    
frontend_profile_user:
    locales:  { en: "/profile/", es: "/perfil/", de: "/profil/" }
    defaults: { _controller: frontEndBundle:user:profile }
    
frontend_change_password_start_user:
    locales:  { en: "/user/change_password/", es: "/usuario/cambiar_clave/", de: "/benutzer/passwort_aendern/" }
    defaults: { _controller: frontEndBundle:user:change_password_start }