frontend_list_faq:
    locales:  { en: "/faq/", es: "/faq/",de: "/faq/" }
    defaults: { _controller: FrontEndBundle:Faq:list }

frontend_filter_faq_callback:
    locales:  { en: "/filter-faqs/", es: "/filtrar-faqs/",de: "/filter-faqs/" }
    defaults: { _controller: FrontEndBundle:Faq:filter }
