frontend_mycasarenta_index:
    locales:  { en: "/app/mycasarenta", es: "/app/mycasarenta", de: "/app/mycasarenta", fr: "/app/mycasarenta", it: "/app/mycasarenta" }
    defaults: { _controller: FrontEndBundle:MyCasaRenta:index}
