frontend_payment_poll_payment:
    pattern:  /payment/poll-payment/{bookingId}
    defaults: { _controller: FrontEndBundle:Payment:pollPayment, bookingId: 0 }

frontend_payment_skrill:
    pattern:  /payment/skrill-payment/{bookingId}
    defaults: { _controller: FrontEndBundle:Payment:skrillPayment, bookingId: 0}

frontend_payment_skrill_return:
    pattern:  /payment/skrill-return/{bookingId}
    defaults: { _controller: FrontEndBundle:Payment:skrillReturn, bookingId: 0}

frontend_payment_skrill_cancel:
    pattern:  /payment/skrill-cancel
    defaults: { _controller: FrontEndBundle:Payment:skrillCancel }

frontend_payment_skrill_status:
    pattern:  /skrill/status
    defaults: { _controller: FrontEndBundle:Payment:skrillStatus }

frontend_payment_skrill_test_response:
    pattern:  /payment/skrill-test-response/{status}
    defaults: { _controller: FrontEndBundle:Payment:skrillTestResponse, status: 'no status' }

frontend_payment_skrill_test_status:
    pattern:  /payment/skrill-test-status/{bookingId}/{status}
    defaults: { _controller: FrontEndBundle:Payment:skrillSendTestPostRequest, bookingId: 0, status: 0 }

frontend_payment_skrill_test_payment:
    pattern:  /payment/skrill-test-payment/{bookingId}
    defaults: { _controller: FrontEndBundle:Payment:skrillTestPayment, bookingId: 0 }

