frontend_welcome:
    pattern:  /welcome/
    defaults: { _controller: frontEndBundle:public:welcome }

frontend_destination:
    resource: "@frontEndBundle/Resources/config/routingFrontendDestination.yml"

frontend_municipality:
    resource: "@frontEndBundle/Resources/config/routingFrontendMunicipality.yml"

frontend_ownership:
    resource: "@frontEndBundle/Resources/config/routingFrontendOwnership.yml"
    
frontend_comment:
    resource: "@frontEndBundle/Resources/config/routingFrontendComment.yml"
    
frontend_user:
    resource: "@frontEndBundle/Resources/config/routingFrontendUser.yml"

frontend_reservation:
    resource: "@frontEndBundle/Resources/config/routingFrontendReservation.yml"
    prefix:   user/reservation/
    
frontend_currency:
    resource: "@frontEndBundle/Resources/config/routingFrontendCurrency.yml"

frontend_information:
    resource: "@frontEndBundle/Resources/config/routingFrontendInformation.yml"
    
frontend_faq:
    resource: "@frontEndBundle/Resources/config/routingFrontendFaq.yml"

frontend_mycasatrip:
    resource: "@frontEndBundle/Resources/config/routingFrontendMyCasaTrip.yml"
    prefix: mycasatrip/

frontend_favorite:
    resource: "@frontEndBundle/Resources/config/routingFrontendFavorite.yml"

frontend_payment:
    resource: "@frontEndBundle/Resources/config/routingFrontendPayment.yml"
