frontend_review_reservation:
    pattern:  /review/
    defaults: { _controller: frontEndBundle:reservation:review }

frontend_add_to_cart_reservation:
    pattern:  /add/{id_ownership}
    defaults: { _controller: frontEndBundle:reservation:add_to_cart }

frontend_remove_from_cart_reservation:
    pattern:  /remove/{data}
    defaults: { _controller: frontEndBundle:reservation:remove_from_cart }

frontend_remove_cart_reservation:
    pattern:  /clear/
    defaults: { _controller: frontEndBundle:reservation:clear }

frontend_review_confirm_reservation:
    pattern:  /check_review/
    defaults: { _controller: frontEndBundle:reservation:review_confirm }

frontend_redirect_reservation_reservation:
    pattern:  /reservation_redirect/
    defaults: { _controller: frontEndBundle:reservation:redirect_reservation_reservation }

frontend_reservation_reservation:
    pattern:  /reservation/
    defaults: { _controller: frontEndBundle:reservation:reservation_reservation }

frontend_confirmation_reservation:
    pattern:  /confirmation/{id_booking}/
    defaults: { _controller: frontEndBundle:reservation:confirmation }

frontend_view_confirmation_reservation:
    pattern:  /confirmation_view/{id_booking}/
    defaults: { _controller: frontEndBundle:reservation:view_confirmation }
