frontend_website_migration_homepage:
  pattern: /{locale}/index.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_accommdation_details:
  pattern: /{locale}/propiedad/detalle.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_search_ownership}

frontend_website_migration_destinations:
  pattern: /{locale}/destinos.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_list_destinations}

frontend_website_migration_destination_details:
  pattern: /{locale}/destino/detalle.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_list_destinations}

frontend_website_migration_search_accommodations:
  pattern: /{locale}/busqueda.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_search_ownership}

frontend_website_migration_search_destinations:
  pattern: /{locale}/busqueda_por_destino.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_list_destinations}

frontend_website_migration_security:
  pattern: /web/imagen_de_seguridad.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_not_found:
  pattern: /{locale}/pag404.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_reservation_form:
  pattern: /{locale}/form_reservar.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_ajax:
  pattern: /{locale}/ajax.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_answer:
  pattern: /{locale}/antwort.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_photo_gallery:
  pattern: /{locale}/galeria_de_fotos.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_top_accommodations:
  pattern: /{locale}/resultados/top_de_propiedades.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_voted_best_list_ownership}

frontend_website_migration_select_processing:
  pattern: /{locale}/select_dependientes_proceso.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_welcome}

frontend_website_migration_contact:
  pattern: /{locale}/contacto.php
  defaults: { _controller: frontEndBundle:websiteMigration:permanentRedirect, redirectTo: frontend_contact_user}
