frontend_review_confirm_reservation:
    locales:  { en: "user/reservation/check-confirm/", es: "usuario/reservacion/chequear-confirmacion/", de: "user/reservation/check-confirm/" }
    defaults: { _controller: FrontEndBundle:Reservation:review_confirm }

frontend_review_confirm_submit:
    pattern:  review_submit
    defaults: { _controller: FrontEndBundle:Reservation:review_confirm_submit }

frontend_redirect_reservation_reservation:
    locales:  { en: "user/reservation/redirect/", es: "usuario/reservacion/redireccionar/", de: "user/reservation/redirect/" }
    defaults: { _controller: FrontEndBundle:Reservation:redirect_reservation_reservation }

frontend_reservation_reservation:
    locales:  { en: "user/reservation/", es: "usuario/reservacion/", de: "user/reservation/" }
    defaults: { _controller: FrontEndBundle:Reservation:reservation_reservation }

frontend_confirmation_reservation:
    locales:  { en: "user/payment/{id_booking}/", es: "usuario/pago/{id_booking}/", de: "user/payment/{id_booking}/" }
    defaults: { _controller: FrontEndBundle:Reservation:confirmation }

frontend_view_confirmation_reservation:
    locales:  { en: "user/reservation/view/{id_booking}/", es: "usuario/reservacion/detalles/{id_booking}/", de: "user/reservation/view/{id_booking}/" }
    defaults: { _controller: FrontEndBundle:Reservation:view_confirmation }

frontend_boucher_reservation:
    locales:  { en: "user/confirmation/{id_booking}/", es: "usuario/confirmacion/{id_booking}/", de: "user/confirmation/{id_booking}/" }
    defaults: { _controller: FrontEndBundle:Reservation:generatePdfVoucher }


