frontend_review_reservation:
    pattern:  /review/
    defaults: { _controller: frontEndBundle:reservation:review }

frontend_add_to_cart_reservation:
    pattern:  /add/{id_ownership}
    defaults: { _controller: frontEndBundle:reservation:add_to_cart }

frontend_remove_cart_reservation:
    pattern:  /clear/
    defaults: { _controller: frontEndBundle:reservation:clear }

frontend_review_confirm_reservation:
    pattern:  /check/{id_ownership}/{data}
    defaults: { _controller: frontEndBundle:reservation:review_confirm }
