parameters:
#    front_end.example.class: MyCp\FrontEndBundle\Example

services:
#    front_end.example:
#        class: %front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
