parameters:

   front_end.services.booking.class: MyCp\FrontEndBundle\Service\BookingService
   front_end.services.pdf.class: MyCp\FrontEndBundle\Service\PdfService

services:
#    front_end.example:
#        class: %front_end.example.class%
#        arguments:
    front_end.services.pdf:
        class: %front_end.services.pdf.class%
        arguments: ["%kernel.root_dir%/config/dompdf_config.inc.php"]

    front_end.services.booking:
        class: %front_end.services.booking.class%
        arguments: [@doctrine.orm.entity_manager, "%configuration.service.fee%", "%configuration.dir.vouchers%","%configuration.triple.room.charge%", @mycp.service.zip, @mycp.notification.service]
        calls:
            - [ setContainer, [ @service_container ] ]

    front_end.services.contact:
        class: MyCp\FrontEndBundle\Service\ContactService
        arguments: ["%configuration.dir.additionalsFiles%"]
        calls:
            - [ setContainer, [ @service_container ] ]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    mycp.logger:
            class: MyCp\FrontEndBundle\Helpers\Logger
            arguments: ["%kernel.root_dir%"]
