parameters:

   front_end.services.booking.class: MyCp\FrontEndBundle\Service\BookingService
   front_end.services.pdf.class: MyCp\FrontEndBundle\Service\PdfService

services:
#    front_end.example:
#        class: %front_end.example.class%
#        arguments:

    front_end.services.pdf:
        class: %front_end.services.pdf.class%
        arguments: ["%kernel.root_dir%/config/dompdf_config.inc.php"]

    front_end.services.booking:
        class: %front_end.services.booking.class%
        arguments: [@doctrine.orm.entity_manager, "%configuration.service.fee%", "%kernel.root_dir%/../tmp/vouchers/"]
        calls:
            - [ setContainer, [ @service_container ] ]
