parameters:

   front_end.services.reservation.class: MyCp\FrontEndBundle\Service\ReservationService

services:
#    front_end.example:
#        class: %front_end.example.class%
#        arguments:

    front_end.services.reservation:
        class: %front_end.services.reservation.class%
        arguments: [@doctrine.orm.entity_manager, "10"]
        calls:
            - [ setContainer, [ @service_container ] ]
