mycp_list_mail_list:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendMailList:list, items_per_page:20 }

mycp_add_mail_list:
    pattern:  /add
    defaults: { _controller: mycpBundle:BackendMailList:add }

mycp_edit_mail_list:
    pattern:  /edit/{listId}
    defaults: { _controller: mycpBundle:BackendMailList:edit }

mycp_delete_mail_list:
    pattern:  /delete/{listId}
    defaults: { _controller: mycpBundle:BackendMailList:delete }

mycp_list_mail_list_user:
    pattern:  /users/{mailList}/{items_per_page}
    defaults: { _controller: mycpBundle:BackendMailList:users, items_per_page:20 }

mycp_add_mail_list_user:
    pattern:  /add/user/{mailList}
    defaults: { _controller: mycpBundle:BackendMailList:addUser }

mycp_delete_mail_list_user:
    pattern:  /delete/user/{mailListUserId}
    defaults: { _controller: mycpBundle:BackendMailList:deleteUser }

