mycp_list_metatags:
    pattern:  /list/
    defaults: { _controller: mycpBundle:BackendMeta:list}

mycp_edit_metatags:
    pattern:  /edit/{meta_id}
    defaults: { _controller: mycpBundle:BackendMeta:edit}