mycp_test_home:
    pattern:  /home/
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:home}

mycp_test_lastChanceToBook:
    pattern:  /last-chance-to-book/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:lastChanceToBook}

mycp_test_lastChanceToBook_send:
    pattern:  /last-chance-to-book-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:lastChanceToBookSend, mail:null}
    
mycp_test_newsletter:
    pattern:  /newsletter-mail/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:newsletterMail}

mycp_test_newsletter_send:
    pattern:  /newsletter-mail-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:newsletterMailSend, mail:null}

mycp_test_accommodation_still_available:
    pattern:  /accommodation-still-available/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:accommodationStillAvailable}

mycp_test_accommodation_still_available_send:
    pattern:  /accommodation-still-available-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:accommodationStillAvailableSend, mail:null}

mycp_test_not_available:
    pattern:  /not-available/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:notAvailable}

mycp_test_not_available_send:
    pattern:  /not-available-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:notAvailableSend, mail:null}

mycp_test_activate_user_reminder_account:
    pattern:  /activate-account-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccountReminder}

mycp_test_activate_user_reminder_account_send:
    pattern:  /activate-account-reminder-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccountReminderSend, mail:null}

mycp_test_activate_user_account:
    pattern:  /activate-account/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccount}

mycp_test_activate_user_account_send:
    pattern:  /activate-account-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccountSend, mail:null}

mycp_test_activate_user_last_reminder_account:
    pattern:  /activate-account-last-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccountLastReminder}

mycp_test_activate_user_last_reminder_account_send:
    pattern:  /activate-account-last-reminder-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccountLastReminderSend, mail:null}

mycp_test_cart_full_reminder:
    pattern:  /cart-full-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:cartFullReminder}
    
mycp_test_cart_full_reminder_send:
    pattern:  /cart-full-reminder-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:cartFullReminderSend, mail:null}

mycp_test_feedback_reminder:
    pattern:  /feedback-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:feedbackReminder}
    
mycp_test_feedback_reminder_send:
    pattern:  /feedback-reminder-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:feedbackReminderSend, mail:null}
    
mycp_test_check_available_rt:
    pattern:  /check-available/{casId}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:checkAvailable, casId:null}

mycp_test_accommodation_notification_rt:
    pattern:  /accommodation-notification
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:accommodationNotification}

mycp_test_send_voucher_rt:
    pattern:  /send-voucher/{reservation}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:sendVoucher, reservation: null, mail:null}

mycp_test_view_voucher_rt:
    pattern:  /view-voucher/{reservation}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:viewVoucher, reservation: null}

mycp_test_send_directory_rt:
    pattern:  /send-directory/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:sendDirectory, mail:null}

mycp_test_view_confirmation_payment_rt:
    pattern:  /confirmation-payment/{booking}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:confirmationPayment, booking: null}

mycp_test_view_confirmation_payment_owner:
    pattern:  /confirmation-payment-owner/{booking}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:confirmationPaymentToOwner, booking: null}

mycp_test_template:
    pattern:  /test-template
    pattern:  /test-template
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:testTemplate}

mycp_test_new_offer:
    pattern:  /newoffer-mail/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:newOfferMail}

mycp_test_new_offer_send:
    pattern:  /newoffer-mail-send/{langCode}/{newMethod}/{mail}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:newOfferMailSend, mail:null}

mycp_test_newsletter_command:
    pattern:  /newsletter
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:newsletter}