mycp_list_agency:
    pattern:  /list/{items_per_page}/{filter_code}/{filter_active}/{filter_category}/{filter_province}/{filter_municipality}/{filter_destination}/{filter_type}/{filter_name}/{filter_saler}/{filter_visit_date}/{filter_other}/{filter_commission}
    defaults: { _controller: mycpBundle:BackendAgency:list_Agency, items_per_page: 100,filter_code:'',filter_active:'',filter_category:'',filter_province:'',filter_municipality:'',filter_destination:'',filter_type:'',filter_name:'', filter_saler:'', filter_visit_date:'', filter_other:'', filter_commission:''}

mycp_details_agency:
    pattern:  /details/{id}
    defaults: { _controller: mycpBundle:BackendAgency:details_Agency, id:''}

mycp_edit_agency:
    pattern:  /edit/{id}
    defaults: { _controller: mycpBundle:BackendAgency:edit_Agency, id:''}

mycp_enable_agency:
    pattern:  /enable/{id}/{activar}
    defaults: { _controller: mycpBundle:BackendAgency:enable_Agency, id:'',activar:''}
