mycp_set_img_order_utils:
    pattern:  /set_img_order/{ids}
    defaults: { _controller: mycpBundle:BackendUtils:set_img_order}
    
mycp_process_images:
    pattern:  /process_images/
    defaults: { _controller: mycpBundle:BackendUtils:process_images}