mycp_list_awards:
    pattern:  /list
    defaults: { _controller: mycpBundle:BackendAward:list, items_per_page: 100}

mycp_new_award:
    pattern:  /new
    defaults: { _controller: mycpBundle:BackendAward:new }

mycp_edit_award:
    pattern:  /edit/{id}
    defaults: { _controller: mycpBundle:BackendAward:edit }

mycp_delete_award:
    pattern:  /delete/{id}
    defaults: { _controller: mycpBundle:BackendAward:delete }

