mycp_list_payments_pending_agency:
    pattern:  /list/{items_per_page}/{filter_number}/{filter_code}/{filter_method}/{filter_payment_date_from}/{filter_payment_date_to}/{filter_type}/{filter_destination}/{filter_booking}/{filter_accommodation}/{filter_reservation}
    defaults: { _controller: mycpBundle:BackendPendingPaymentAgency:list, items_per_page: 100,filter_number:'',filter_code:'',filter_method:'', filter_payment_date_from:'',filter_payment_date_to:'', filter_type:'', filter_destination:'', filter_booking:'', filter_accommodation:'', filter_reservation:''}


mycp_details_payment_pending_agency:
    pattern:  /detail/{id}
    defaults: { _controller: mycpBundle:BackendPendingPaymentAgency:detail }

mycp_edit_payment_pending_agency:
    pattern:  /edit/{id}
    defaults: { _controller: mycpBundle:BackendPendingPaymentAgency:edit }

mycp_save_payment_pending_agency:
    pattern:  /save
    defaults: { _controller: mycpBundle:BackendPendingPaymentAgency:save }

mycp_export_list_payment_pending_agency:
    pattern:  /export/{filter_number}/{filter_code}/{filter_method}/{filter_payment_date_from}/{filter_payment_date_to}/{filter_payment_date_to}/{filter_type}/{filter_destination}/{filter_booking}/{filter_accommodation}/{filter_reservation}
    defaults: { _controller: mycpBundle:BackendPendingPaymentAgency:export,filter_number:'',filter_code:'',filter_method:'', filter_payment_date_from:'',filter_payment_date_to:'', filter_type:'', filter_destination:'', filter_booking:'', filter_accommodation:'', filter_reservation:''}
