mycp_new_reservation:
    pattern:  /new/
    defaults: { _controller: mycpBundle:BackendReservation:new_reservation }

mycp_delete_reservation:
    pattern:  /delete/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:delete_reservation }

mycp_list_reservations:
    pattern:  /list/{items_per_page}/{filter_date_reserve}/{filter_offer_number}/{filter_reference}/{filter_date_from}/{filter_date_to}
    defaults: { _controller: mycpBundle:BackendReservation:list_reservations,items_per_page:100,filter_date_reserve:'',filter_offer_number:'',filter_reference:'',filter_date_from:'',filter_date_to:''}

mycp_edit_reservation:
    pattern:  /edit/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:edit_reservation }

mycp_get_rooms_by_ownership:
    pattern:  /get_rooms/{id_ownership}/{selected_room}
    defaults: { _controller: mycpBundle:BackendReservation:get_rooms_by_ownership,selected_room:''}

