mycp_list_ownerships:
    pattern:  /list/{items_per_page}/{filter_code}/{filter_active}/{filter_category}/{filter_province}/{filter_municipality}/{filter_destination}/{filter_type}/{filter_name}/{filter_saler}/{filter_visit_date}/{filter_other}
    defaults: { _controller: mycpBundle:BackendOwnership:list_ownerships, items_per_page: 100,filter_code:'',filter_active:'',filter_category:'',filter_province:'',filter_municipality:'',filter_destination:'',filter_type:'',filter_name:'', filter_saler:'', filter_visit_date:'', filter_other:''}

mycp_new_ownership:
    pattern:  /new/
    defaults: { _controller: mycpBundle:BackendOwnership:new_ownership }

mycp_edit_ownership:
    pattern:  /edit/{id_ownership}
    defaults: { _controller: mycpBundle:BackendOwnership:edit_ownership }

mycp_delete_ownership:
    pattern:  /delete/{id_ownership}
    defaults: { _controller: mycpBundle:BackendOwnership:delete_ownership }

mycp_active_room:
    pattern: /active/room/{id_room}/{activate}
    defaults: {_controller: mycpBundle:BackendOwnership:activeRoom}

mycp_new_photos_ownership:
    pattern:   /photos/new/{id_ownership}
    defaults: { _controller: mycpBundle:BackendOwnership:new_photos}

mycp_list_photos_ownership:
    pattern:  /photos/{id_ownership}/{items_per_page}
    defaults: { _controller: mycpBundle:BackendOwnership:list_photos , items_per_page:10}

mycp_delete_photos_ownership:
    pattern:  /delete_photo/{id_ownership}/{id_photo}
    defaults: { _controller: mycpBundle:BackendOwnership:delete_photo }

mycp_edit_photos_ownership:
    pattern:  /edit_photo/{id_photo}/{id_ownership}
    defaults: { _controller: mycpBundle:BackendOwnership:edit_photo }

mycp_send_ownership:
    pattern:  /send/{own_id}
    defaults: { _controller: mycpBundle:BackendOwnership:send_ownership }

mycp_publish_ownership:
    pattern:  /publish/{idOwnership}
    defaults: { _controller: mycpBundle:BackendOwnership:publish }

mycp_delete_multiple_photo_ownership_callback:
    pattern:  /delete-multiple-photos-callback/{idOwnership}
    defaults: { _controller: mycpBundle:BackendOwnership:deleteMultiplesPhotosCallback }

mycp_batch_process_ownership:
    pattern:  /batch-process/{items_per_page}/{filter_status}/{filter_start_date}
    defaults: { _controller: mycpBundle:BackendOwnership:batchProcess, items_per_page: 100,filter_status:'',filter_start_date:'' }
