mycp_list_readonly_reservations:
    pattern:  /list/{items_per_page}/{filter_date_reserve}/{filter_offer_number}/{filter_reference}/{filter_date_from}/{filter_date_to}/{sort_by}/{filter_booking_number}/{filter_status}
    defaults: { _controller: mycpBundle:LodgingReservation:list_reservations,items_per_page:100,filter_date_reserve:'',filter_offer_number:'',filter_reference:'',filter_date_from:'',filter_date_to:'',filter_booking_number:'', filter_status:'',sort_by:0}

mycp_details_readonly_reservation:
    pattern:  /details/{id_reservation}/{from_calendar}
    defaults: { _controller: mycpBundle:LodgingReservation:details_reservation, from_calendar: 0 }

mycp_list_readonly_reservations_user:
    pattern:  /users/list/{items_per_page}/{filter_user_name}/{filter_user_email}/{filter_user_country}/{sort_by}
    defaults: { _controller: mycpBundle:LodgingReservation:listReservationsByUser,items_per_page:100,filter_user_name:'',filter_user_email:'',filter_user_country:'',sort_by:0}

mycp_details_readonly_reservation_partial:
    pattern:  /details_partial/{id_reservation}
    defaults: { _controller: mycpBundle:LodgingReservation:detailsReservationPartial }

mycp_details_readonly_client_reservation:
    pattern:  /client/details/{id_client}
    defaults: { _controller: mycpBundle:LodgingReservation:detailsClientReservation }