mycp_list_transfer:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendTransfer:list_transfer,items_per_page:10}

mycp_edit_transfer:
    pattern:  /edit/{id_transfer}
    defaults: { _controller: mycpBundle:BackendTransfer:edit_transfer}

mycp_new_transfer:
    pattern:  /new
    defaults: { _controller: mycpBundle:BackendTransfer:new_transfer}

mycp_delete_transfer:
    pattern:  /delete/{id_transfer}
    defaults: { _controller: mycpBundle:BackendTransfer:delete_transfer}
