mycp_list_languages:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendLanguage:list_languages,items_per_page:10}

mycp_edit_language:
    pattern:  /edit/{id_language}
    defaults: { _controller: mycpBundle:BackendLanguage:edit_language}

mycp_new_language:
    pattern:  /new
    defaults: { _controller: mycpBundle:BackendLanguage:new_language}

mycp_delete_language:
    pattern:  /delete/{id_language}
    defaults: { _controller: mycpBundle:BackendLanguage:delete_language}
