mycp_list_payments_pending_tourist:
    pattern:  /list/{items_per_page}/{filter_number}/{filter_code}/{filter_method}/{filter_payment_date_from}/{filter_payment_date_to}
    defaults: { _controller: mycpBundle:BackendPendingPayTourist:list, items_per_page: 100,filter_number:'',filter_code:'',filter_method:'', filter_payment_date_from:'',filter_payment_date_to:''}


mycp_details_payment_pending_tourist:
    pattern:  /detail/{id}
    defaults: { _controller: mycpBundle:BackendPendingPayTourist:detail }

mycp_edit_payment_pending_tourist:
    pattern:  /edit/{id}
    defaults: { _controller: mycpBundle:BackendPendingPayTourist:edit }

mycp_save_payment_pending_tourist:
    pattern:  /save
    defaults: { _controller: mycpBundle:BackendPendingPayTourist:save }