mycp_reports:
    pattern:  /
    defaults: { _controller: mycpBundle:BackendReport:reports}

mycp_reports_daily_in_place_clients:
    pattern:  /clients/daily-in-place/{date}
    defaults: { _controller: mycpBundle:BackendReport:dailyInPlaceClients,date:''}

mycp_reports_daily_in_place_clients_excel:
    pattern:  /clients/excel-daily-in-place/{report}/{date}
    defaults: { _controller: mycpBundle:BackendReport:dailyInPlaceClientsExcel,date:'', report:''}

mycp_reports_ownership_general_stats:
    pattern:  /ownership/general-stats/{location}
    defaults: { _controller: mycpBundle:BackendReport:ownershipGeneralStats,location:''}

mycp_reports_ownership_general_stats_excel:
    pattern:  /ownership/general-stats-excel/{report}/{province}/{municipality}
    defaults: { _controller: mycpBundle:BackendReport:ownershipGeneralStatsExcel, report:'',province:'',municipality:''}

mycp_reports_ownership_general_stats_links:
    pattern:  /ownership/general-stats-link/{nomenclator}/{province}/{municipality}
    defaults: { _controller: mycpBundle:BackendReport:ownershipGeneralStatsLink, province:'',municipality:''}

mycp_reports_ownership_vsReservations_stats:
    pattern:  /ownership/vsReservation/{from_date}/{to_date}/{location_full}
    defaults: { _controller: mycpBundle:BackendReport:ownershipVsReservationsStats,location_full:'',from_date:'',to_date:''}

mycp_reports_ownership_vsReservations_stats_excel:
    pattern:  ownership/vsReservation-excel/{report}/{from_date}/{to_date}/{province}/{municipality}/{destination}
    defaults: { _controller: mycpBundle:BackendReport:ownershipVsReservationsStatsExcel, report:'',from_date:'',to_date:'',province:'',municipality:'',destination:''}

mycp_get_report_by_category:
    pattern:  /get-by-category
    defaults: { _controller: mycpBundle:BackendReport:getByCategoryCallback}

mycp_get_report_parameters:
    pattern:  /get-parameters
    defaults: { _controller: mycpBundle:BackendReport:getParametersCallback}

mycp_reports_ownership_general_list_excel:
    pattern:  /ownership/general-list-excel/{nomenclator}/{province}/{municipality}
    defaults: { _controller: mycpBundle:BackendReport:ownershipGeneralListExcel, nomenclator:'',province:'',municipality:''}

mycp_reports_ownership_vsReservations_stats_total:
    pattern:  /ownership/vsReservation-total/{filter_province}/{filter_municipality}/{filter_destination}/{from_date}/{to_date}
    defaults: { _controller: mycpBundle:BackendReport:ownershipVsReservationsStatsTotal,filter_province:'',filter_municipality:'',filter_destination:'',from_date:'',to_date:''}

mycp_reports_ownership_vsReservations_stats_accommodation:
    pattern:  /ownership/vsReservation-accommodation
    defaults: { _controller: mycpBundle:BackendReport:ownershipVsReservationsStatsAccommodation}

mycp_reports_ownership_sales_summary:
    pattern:  /ownership/sales-summary
    defaults: { _controller: mycpBundle:BackendReport:ownershipSalesReport}
mycp_reports_reservations_byclient_summary:
    pattern:  /reservations/summary/{from_date}/{to_date}
    defaults: { _controller: mycpBundle:BackendReport:reservationsByClientReport ,from_date:'',to_date:''}
mycp_reports_reservations_byclient_summary_excel:
    pattern:  /reservations/summary_to_excel/{report}/{from_date}/{to_date}
    defaults: { _controller: mycpBundle:BackendReport:reservationsByClientReportExcel, report: '' ,from_date:'',to_date:''}
mycp_reports_bookings_summary:
    pattern:  /bookings/summary/{from_date}/{to_date}
    defaults: { _controller: mycpBundle:BackendReport:bookingSummaryReport ,from_date:'',to_date:''}
mycp_reports_bookings_summary_excel:
    pattern:  /bookings/summary_to_excel/{report}/{from_date}/{to_date}
    defaults: { _controller: mycpBundle:BackendReport:bookingsSummaryReportExcel, report: '' ,from_date:'',to_date:''}
mycp_report_reservations_booking:
    pattern:  /booking/list/{filter_date_booking_from}/{filter_date_booking_to}/{filter_booking_number}/{filter_user_booking}/{filter_currency}/{filter_reservation}/{filter_ownership}
    defaults: { _controller: mycpBundle:BackendReport:list_reservations_booking, filter_date_booking_from:'',filter_date_booking_to: '', filter_booking_number:'',filter_user_booking:'', filter_reservation:'', filter_ownership:'', filter_currency:''}
mycp_report_reservations_booking_to_excel:
    pattern:  /booking/excel/{filter_date_booking_from}/{filter_date_booking_to}/{filter_booking_number}/{filter_user_booking}/{filter_currency}/{filter_reservation}/{filter_ownership}
    defaults: { _controller: mycpBundle:BackendReport:list_reservations_booking_to_excel, filter_date_booking_from:'',filter_date_booking_to: '', filter_booking_number:'',filter_user_booking:'', filter_reservation:'', filter_ownership:'', filter_currency:''}
mycp_report_reservations_client_details:
    pattern:  /reservations/client/{id_client}/{filter_date_from}/{filter_date_to}/{filter_reservation_status}/{filter_province}/{filter_destination}/{filter_nights}
    defaults: { _controller: mycpBundle:BackendReport:details_client_reservation, filter_date_from:'',filter_date_to: '', filter_reservation_status:'',filter_province:'', filter_destination:'', filter_nights:''}
mycp_report_reservations_client_details_to_excel:
    pattern:  /reservations/client_excel/{id_client}/{filter_date_from}/{filter_date_to}/{filter_reservation_status}/{filter_province}/{filter_destination}/{filter_nights}
    defaults: { _controller: mycpBundle:BackendReport:details_client_reservation_to_excel, filter_date_from:'',filter_date_to: '', filter_reservation_status:'',filter_province:'', filter_destination:'', filter_nights:''}
