mycp_list_override_user:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendOverride:list, items_per_page: 100}

mycp_add_override_user:
    pattern:  /add
    defaults: { _controller: mycpBundle:BackendOverride:add }

mycp_edit_override_user:
    pattern:  /edit/{id}
    defaults: { _controller: mycpBundle:BackendOverride:edit }

mycp_delete_override_user:
    pattern:  /delete/{id}
    defaults: { _controller: mycpBundle:BackendOverride:delete }

