mycp_test_home:
    pattern:  /home/
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:home}

mycp_test_lastChanceToBook:
    pattern:  /last-chance-to-book/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:lastChanceToBook}

mycp_test_accommodation_still_available:
    pattern:  /accommodation-still-available/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:accommodationStillAvailable}

mycp_test_not_available:
    pattern:  /not-available/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:notAvailable}

mycp_test_activate_user_reminder_account:
    pattern:  /activate-account-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccountReminder}

mycp_test_activate_user_account:
    pattern:  /activate-account/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccount}

mycp_test_activate_user_last_reminder_account:
    pattern:  /activate-account-last-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:activateAccountLastReminder}

mycp_test_cart_full_reminder:
    pattern:  /cart-full-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:cartFullReminder}

mycp_test_feedback_reminder:
    pattern:  /feedback-reminder/{langCode}
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:feedbackReminder}

mycp_test_check_available_rt:
    pattern:  /check-available
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:checkAvailable}

mycp_test_accommodation_notification_rt:
    pattern:  /accommodation-notification
    defaults: { _controller: mycpBundle:BackendTestEmailTemplate:accommodationNotification}