mycp_new_reservation:
    pattern:  /new/
    defaults: { _controller: mycpBundle:BackendReservation:new_reservation }

mycp_delete_reservation:
    pattern:  /delete/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:delete_reservation }

mycp_list_reservations:
    pattern:  /list/{items_per_page}/{filter_date_reserve}/{filter_offer_number}/{filter_reference}/{filter_date_from}/{filter_date_to}/{sort_by}/{filter_booking_number}/{filter_status}
    defaults: { _controller: mycpBundle:BackendReservation:list_reservations,items_per_page:100,filter_date_reserve:'',filter_offer_number:'',filter_reference:'',filter_date_from:'',filter_date_to:'',filter_booking_number:'', filter_status:'',sort_by:0}

mycp_list_reservations_booking:
    pattern:  /booking/list/{items_per_page}/{filter_booking_number}/{filter_date_booking}/{filter_user_booking}/{filter_arrive_date_booking}
    defaults: { _controller: mycpBundle:BackendReservation:list_reservations_booking,items_per_page:100,filter_booking_number:'',filter_date_booking:'',filter_user_booking:'',filter_arrive_date_booking:''}

mycp_details_reservations_booking:
    pattern:  /booking/details/{id_booking}
    defaults: { _controller: mycpBundle:BackendReservation:details_booking }

mycp_list_reservations_user:
    pattern:  /users/list/{items_per_page}/{filter_user_name}/{filter_user_email}/{filter_user_city}/{filter_user_country}/{sort_by}
    defaults: { _controller: mycpBundle:BackendReservation:list_reservations_user,items_per_page:100,filter_user_name:'',filter_user_email:'',filter_user_city:'',filter_user_country:'',sort_by:0}

mycp_edit_reservation:
    pattern:  /edit/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:edit_reservation }

mycp_details_reservation:
    pattern:  /details/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:details_reservation }

mycp_new_offer_reservation:
    pattern:  /new_offer/{id_tourist}/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:new_offer }

mycp_send_reservation:
    pattern:  /send/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:send_reservation }


mycp_details_reservation_partial:
    pattern:  /details_partial/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:details_reservation_partial }

mycp_details_client_reservation:
    pattern:  /client/details/{id_client}
    defaults: { _controller: mycpBundle:BackendReservation:details_client_reservation }

mycp_get_rooms_by_ownership:
    pattern:  /get_rooms/{id_ownership}/{selected_room}
    defaults: { _controller: mycpBundle:BackendReservation:get_rooms_by_ownership,selected_room:''}

mycp_set_not_available_reservation_callback:
    pattern:  /set_not_available/
    defaults: { _controller: mycpBundle:BackendReservation:setNotAvailableCallback }

mycp_send_voucher_reservation:
    pattern:  /send_voucher/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:sendVoucherToReservationTeam }

mycp_list_reservations_checkin:
    pattern:  /check-in/{startDate}
    defaults: { _controller: mycpBundle:BackendReservation:checkin,startDate:'' }

mycp_changes_dates_reservation:
    pattern:  /change_dates/{id_tourist}/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:changeDates }
