update_route:
    pattern:  /upd_reservations/
    defaults: { _controller: mycpBundle:MycpCF:mycpOfflineReservationsUpd}
    
commit_route:
    pattern:  /commit_reservations/
    defaults: { _controller: mycpBundle:MycpCF:mycpOfflineReservationsCommit}    
    
upd_users_route:
    pattern:  /upd_users/
    defaults: { _controller: mycpBundle:MycpCF:mycpOfflineUsersUpd} 
