mycp_accommodations_export_excel:
    pattern:  /excel/accommodations
    defaults: { _controller: mycpBundle:BackendExport:exportAccommodationsToExcel }

mycp_checkin_export_excel:
    pattern:  /excel/check-in/{date}/{sort_by}
    defaults: { _controller: mycpBundle:BackendExport:checkInToExcel}

mycp_download_zip_photo:
    pattern:  /zip-download/photo/{idOwnership}/{ownMycpCode}
    defaults: { _controller: mycpBundle:BackendExport:zipDownloadOwnPhoto}

mycp_download_info:
    pattern:  /download
    defaults: { _controller: mycpBundle:BackendExport:download}

mycp_generate_info_airbnb:
    pattern:  /airbnb-generate
    defaults: { _controller: mycpBundle:BackendExport:airbnbGenerate}

mycp_download_info_airbnb:
    pattern:  /airbnb-download
    defaults: { _controller: mycpBundle:BackendExport:airbnbDownload}

mycp_export_accommodation_list:
    pattern:  /accommodation-list
    defaults: { _controller: mycpBundle:BackendExport:getAccommodations}

mycp_download_single_zip_photo:
    pattern:  /zip-download/single-photo/{idPhoto}/{ownMcpCode}
    defaults: { _controller: mycpBundle:BackendExport:zipDownloadSinglePhoto}

mycp_generate_info_dir:
    pattern:  /dir-generate
    defaults: { _controller: mycpBundle:BackendExport:dirGenerate}

mycp_download_info_dir:
    pattern:  /dir-download
    defaults: { _controller: mycpBundle:BackendExport:dirDownload}