mycp_list_season:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendSeason:list ,items_per_page: 20}
    
mycp_new_season:
    pattern:  /new
    defaults: { _controller: mycpBundle:BackendSeason:new}
    
mycp_edit_season:
    pattern:  /edit/{id_season}
    defaults: { _controller: mycpBundle:BackendSeason:edit}
    
mycp_delete_season:
    pattern:  /delete/{id_season}
    defaults: { _controller: mycpBundle:BackendSeason:delete}