mycp_new_reservation:
    pattern:  /new/
    defaults: { _controller: mycpBundle:BackendReservation:new_reservation }

mycp_delete_reservation:
    pattern:  /delete/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:delete_reservation }

mycp_list_reservations:
    pattern:  /list/{items_per_page}/{filter_date_reserve}/{filter_offer_number}/{filter_reference}/{filter_date_from}/{filter_date_to}/{sort_by}/{filter_booking_number}/{filter_status}
    defaults: { _controller: mycpBundle:BackendReservation:list_reservations,items_per_page:50,filter_date_reserve:'',filter_offer_number:'',filter_reference:'',filter_date_from:'',filter_date_to:'',filter_booking_number:'', filter_status:'',sort_by:0}

mycp_list_reservations_booking:
    pattern:  /booking/list/{items_per_page}/{filter_booking_number}/{filter_date_booking}/{filter_user_booking}/{filter_arrive_date_booking}/{filter_reservation}/{filter_ownership}/{filter_currency}
    defaults: { _controller: mycpBundle:BackendReservation:list_reservations_booking,items_per_page:100,filter_booking_number:'',filter_date_booking:'',filter_user_booking:'',filter_arrive_date_booking:'', filter_reservation:'', filter_ownership:'', filter_currency:''}

mycp_details_reservations_booking:
    pattern:  /booking/details/{id_booking}
    defaults: { _controller: mycpBundle:BackendReservation:details_booking }

mycp_list_reservations_user:
    pattern:  /users/list/{items_per_page}/{filter_user_name}/{filter_user_email}/{filter_user_city}/{filter_user_country}/{sort_by}
    defaults: { _controller: mycpBundle:BackendReservation:list_reservations_user,items_per_page:100,filter_user_name:'',filter_user_email:'',filter_user_city:'',filter_user_country:'',sort_by:0}

mycp_edit_reservation:
    pattern:  /edit/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:edit_reservation }

mycp_details_reservation:
    pattern:  /details/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:details_reservation }

mycp_new_offer_reservation:
    pattern:  /new_offer/{id_tourist}/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:new_offer }

mycp_send_reservation:
    pattern:  /send/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:send_reservation }


mycp_details_reservation_partial:
    pattern:  /details_partial/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:details_reservation_partial }

mycp_details_client_reservation:
    pattern:  /client/details/{id_client}
    defaults: { _controller: mycpBundle:BackendReservation:details_client_reservation }

mycp_get_rooms_by_ownership:
    pattern:  /get_rooms/{id_ownership}/{selected_room}
    defaults: { _controller: mycpBundle:BackendReservation:get_rooms_by_ownership,selected_room:''}

mycp_set_not_available_reservation_callback:
    pattern:  /set_not_available/
    defaults: { _controller: mycpBundle:BackendReservation:setNotAvailableCallback }

mycp_send_voucher_reservation:
    pattern:  /send_voucher/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:sendVoucherToReservationTeam }

mycp_list_reservations_checkin:
    pattern:  /check-in/{startDate}/{sort_by}
    defaults: { _controller: mycpBundle:BackendReservation:checkin,startDate:'',sort_by:'' }

mycp_changes_dates_reservation:
    pattern:  /change_dates/{id_tourist}/{id_reservation}
    defaults: { _controller: mycpBundle:BackendReservation:changeDates }

mycp_new_offer_to_client:
    pattern:  /new-offer-to-client/{idClient}/{attendedDate}
    defaults: { _controller: mycpBundle:BackendReservation:newCleanOffer, idClient:'',attendedDate:'' }

mycp_reservation_bookings_callback:
    pattern:  /reservation-bookings-callback/
    defaults: { _controller: mycpBundle:BackendReservation:getBookingsCallback }

mycp_reservation_logs_callback:
    pattern:  /reservation-logs-callback/
    defaults: { _controller: mycpBundle:BackendReservation:getLogsCallback }

mycp_reservation_sync_payment:
    pattern:  /sync_payment
    defaults: { _controller: mycpBundle:BackendReservation:syncPayments }

mycp_reservation_sync_booking_list:
    pattern:  /sync_bookings/{sinceDate}
    defaults: { _controller: mycpBundle:BackendReservation:syncBookings, sinceDate:'' }

mycp_export_list_reservations:
    pattern:  /export/{filter_date_reserve}/{filter_offer_number}/{filter_reference}/{filter_date_from}/{filter_date_to}/{sort_by}/{filter_booking_number}/{filter_status}
    defaults: { _controller: mycpBundle:BackendReservation:exportReservations,filter_date_reserve:'',filter_offer_number:'',filter_reference:'',filter_date_from:'',filter_date_to:'',filter_booking_number:'', filter_status:'',sort_by:0}

mycp_reservation_notifications_callback:
    pattern:  /reservation-notifications-callback/
    defaults: { _controller: mycpBundle:BackendReservation:getNotificationsCallback }

mycp_list_reservations_byuser:
    pattern:  /by-users/list/{items_per_page}/{filter_name}/{filter_status}/{filter_accommodation}/{filter_destination}/{filter_range_from}/{filter_range_to}
    defaults: { _controller: mycpBundle:BackendReservation:listReservationsByUsers,items_per_page:100,filter_name:'',filter_status:'',filter_accommodation:'',filter_destination:'',filter_range_from:'',filter_range_to:''}

mycp_export_users_reservations:
    pattern:  /export-users/reservations/{idClient}
    defaults: { _controller: mycpBundle:BackendReservation:exportUsersReservations}

mycp_generate_clients_callback:
    pattern:  /generate_client/
    defaults: { _controller: mycpBundle:BackendReservation:generateClientCallback }

mycp_download_clients:
    pattern:  /download_clients
    defaults: { _controller: mycpBundle:BackendReservation:downloadClientCallback}

mycp_send_email_client:
    pattern:  /sender/email/
    defaults: { _controller: mycpBundle:BackendReservation:showModalEmail}

mycp_send_email_destination:
    pattern:  /email/send/destination
    defaults: { _controller: mycpBundle:BackendReservation:sendEmailDestination}

mycp_details_client_reservationAG:
    pattern:  /client/detailsAG/{id_client}
    defaults: { _controller: mycpBundle:BackendReservation:details_client_reservationAg }

mycp_new_offer_to_client_ag:
    pattern:  /new-offer-to-client-ag/{idClient}/{idClientOfAg}/{attendedDate}
    defaults: { _controller: mycpBundle:BackendReservationAg:newCleanOffer, idClient:'', idClientOfAg:'',attendedDate:'' }