mycp_list_override_user:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendOverride:list, items_per_page: 100}

mycp_add_override_user:
    pattern:  /add
    defaults: { _controller: mycpBundle:BackendOverride:add }

mycp_delete_override_user:
    pattern:  /delete/{id}
    defaults: { _controller: mycpBundle:BackendOverride:delete }

mycp_find_user:
    pattern:  /find
    defaults: { _controller: mycpBundle:BackendOverride:find }

mycp_override_user:
    pattern:  /override/{id}
    defaults: { _controller: mycpBundle:BackendOverride:override,id:'' }