mycp_list_touristfailures:
    pattern:  /list/{accommodationId}
    defaults: { _controller: mycpBundle:BackendFailure:list}

mycp_create_touristfailures:
    pattern:  /create/{accommodationId}
    defaults: { _controller: mycpBundle:BackendFailure:create }


mycp_delete_touristfailures:
    pattern:  /delete/{idFailure}
    defaults: { _controller: mycpBundle:BackendFailure:delete }

mycp_list_failures:
    pattern:  /list-general
    defaults: { _controller: mycpBundle:BackendFailure:listGeneral}
