mycp_new_faq:
    pattern:  /new/
    defaults: { _controller: mycpBundle:BackendFAQS:new_faq }

mycp_list_faqs:
    pattern:  /list/{items_per_page}/{filter_name}/{filter_active}/{category}/{sort_by}
    defaults: { _controller: mycpBundle:BackendFAQS:list_faqs , items_per_page: 100,filter_name:'',filter_active:'',category:'',sort_by:'null'}

mycp_edit_faq:
    pattern:  /edit/{id_faq}
    defaults: { _controller: mycpBundle:BackendFAQS:edit_faq }

mycp_edit_category_faq:
    pattern:  /edit_category/{id_category}
    defaults: { _controller: mycpBundle:BackendFAQS:edit_category }

mycp_delete_faq:
    pattern:  /delete/{id_faq}
    defaults: { _controller: mycpBundle:BackendFAQS:delete_faq }

mycp_order_faqs:
    pattern:  /set_faqs_order/{ids}
    defaults: { _controller: mycpBundle:BackendFAQS:set_faqs_order }

mycp_list_category_faq:
    pattern:  /list_categories/{items_per_page}
    defaults: { _controller: mycpBundle:BackendFAQS:list_category ,items_per_page: 10}

mycp_new_category_faq:
    pattern:  /categories/new
    defaults: { _controller: mycpBundle:BackendFAQS:new_category }

mycp_delete_category_faq:
    pattern:  /delete_category/{id_category}
    defaults: { _controller: mycpBundle:BackendFAQS:delete_category }
