mycp_list_municipality:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendMunicipality:list ,items_per_page: 20}

mycp_new_municipality:
    pattern:  /new
    defaults: { _controller: mycpBundle:BackendMunicipality:new}

mycp_edit_municipality:
    pattern:  /edit/{id_municipality}
    defaults: { _controller: mycpBundle:BackendMunicipality:edit}

mycp_delete_municipality:
    pattern:  /delete/{id_municipality}
    defaults: { _controller: mycpBundle:BackendMunicipality:delete}

