mycp_list_currencies:
    pattern:  /list/{items_per_page}
    defaults: { _controller: mycpBundle:BackendCurrency:list_currencies,items_per_page:10}

mycp_edit_currency:
    pattern:  /edit/{id_currency}
    defaults: { _controller: mycpBundle:BackendCurrency:edit_currency}

mycp_new_currency:
    pattern:  /new
    defaults: { _controller: mycpBundle:BackendCurrency:new_currency}

mycp_delete_currency:
    pattern:  /delete/{id_currency}
    defaults: { _controller: mycpBundle:BackendCurrency:delete_currency}

mycp_get_currency_change:
    pattern:  /currency_change
    defaults: { _controller: mycpBundle:BackendCurrency:get_currency_change}
