mycp_list_agency:
    pattern:  /list/{items_per_page}/{filter_name}/{filter_active}/{filter_country}/{filter_date_created}/{filter_owner}/{filter_email}/{filter_package}
    defaults: { _controller: mycpBundle:BackendAgency:list_Agency, items_per_page: 100,filter_name:'',filter_active:'',filter_country:'',filter_date_created:'',filter_owner:'',filter_email:'',filter_package:''}

mycp_active_release:
    pattern:  /active-release/{items_per_page}/{filter_name}/{filter_active}/{filter_country}/{filter_date_created}/{filter_owner}/{filter_email}/{filter_package}
    defaults: { _controller: mycpBundle:BackendAgency:active_release, items_per_page: 100,filter_name:'',filter_active:'',filter_country:'',filter_date_created:'',filter_owner:'',filter_email:'',filter_package:''}

mycp_details_agency:
    pattern:  /details/{id}
    defaults: { _controller: mycpBundle:BackendAgency:details_Agency, id:''}

mycp_edit_agency:
    pattern:  /edit/{id}
    defaults: { _controller: mycpBundle:BackendAgency:edit_Agency, id:''}

mycp_enable_agency:
    pattern:  /enable/{id}/{activar}
    defaults: { _controller: mycpBundle:BackendAgency:enable_Agency, id:'',activar:''}

mycp_list_agency_checkin:
    pattern:  /check-in/{startDate}/{sort_by}
    defaults: { _controller: mycpBundle:BackendReservationAg:checkin,startDate:'',sort_by:'' }
