mycp_list_comments:
    pattern:  /list/{items_per_page}/{filter_ownership}/{filter_user}/{filter_keyword}/{filter_rate}/{sort_by}
    defaults: { _controller: mycpBundle:BackendComment:list_comment, items_per_page: 100,filter_ownership:'',filter_user:'',filter_keyword:'',filter_rate:'',sort_by:'0'}

mycp_edit_comment:
    pattern:  /edit/{return_url}/{id_comment}
    defaults: { _controller: mycpBundle:BackendComment:edit_comment, return_url:'null' }

mycp_delete_comment:
    pattern:  /delete_comment/{return_url}/{id_comment}
    defaults: { _controller: mycpBundle:BackendComment:delete_comment, return_url:'null' }

mycp_new_comment:
    pattern:  /new/
    defaults: { _controller: mycpBundle:BackendComment:new_comment }

mycp_public_comment:
    pattern:  /public/{return_url}/{id_comment}
    defaults: { _controller: mycpBundle:BackendComment:public, return_url:'null' }

mycp_last_comment:
    pattern:  /last/{items_per_page}/{filter_ownership}/{filter_user}/{filter_keyword}/{filter_rate}/{sort_by}
    defaults: { _controller: mycpBundle:BackendComment:last, items_per_page: 100,filter_ownership:'',filter_user:'',filter_keyword:'',filter_rate:'',sort_by:'0'}

mycp_public_selected_callback_comment:
    pattern:  /public_selected/
    defaults: { _controller: mycpBundle:BackendComment:publicSelectedCallback }

mycp_delete_selected_callback_comment:
    pattern:  /delete_selected/
    defaults: { _controller: mycpBundle:BackendComment:deleteSelectedCallback }