parameters:

services:
   mycp.job.user.signupreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "abuc.job.labels.signupreminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: abuc.event.user.signup,  method: onEvent }

   mycp.job.reservation.reminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.reminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.sent_out,  method: onEvent }

   mycp.service.email_manager:
       class: MyCp\mycpBundle\Helpers\EmailManager
       arguments: [@doctrine.orm.entity_manager, @Email, @templating, @translator, @router, @mailer, @swiftmailer.transport.real, @logger, "noreply@mycasaparticular.com", "MyCasaParticular.com", "3"]

   mycp.job.user.latesignupreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.latesignup.reminder", "48 hours"]
       tags:
           - { name: kernel.event_listener, event: abuc.event.user.signup,  method: onEvent }
