parameters:

services:
   mycp.job.user.signupreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "abuc.job.labels.signupreminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: abuc.event.user.signup,  method: onEvent }

   mycp.job.reservation.reminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.reminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.sent_out,  method: onEvent }

   mycp.job.reservation.last.reminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.last.reminder", "42 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.sent_out,  method: onEvent }

   mycp.job.reservation.expired.offer.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.expired.offer.reminder", "48 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.sent_out,  method: onEvent }

   mycp.service.email_manager:
       class: MyCp\mycpBundle\Helpers\EmailManager
       arguments: [@doctrine.orm.entity_manager, @Email, @templating, @translator, @router, @mailer, @swiftmailer.transport.real, @logger, "noreply@mycasaparticular.com", "MyCasaParticular.com", "3"]

   mycp.job.user.latesignupreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.latesignup.reminder", "48 hours"]
       tags:
           - { name: kernel.event_listener, event: abuc.event.user.signup,  method: onEvent }

   mycp.job.user.fullcart.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.fullcart.reminder", "3 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.cart.full,  method: onEvent }

   mycp.job.user.feedback.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.feedback.reminder"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.feedback,  method: onEvent }

   mycp.service.export_to_excel:
       class: MyCp\mycpBundle\Helpers\ExportToExcel
       arguments: [@doctrine.orm.entity_manager, @service_container,"%configuration.dir.excels%"]

   mycp.service.zip:
        class: MyCp\mycpBundle\Helpers\ZipService
        arguments: [@doctrine.orm.entity_manager,@service_container, %ownership.dir.photos.zips%, %ownership.dir.photos%, %ownership.dir.photos.originals%]

   mycp.service.calendar:
       class: MyCp\mycpBundle\Helpers\CalendarManager
       arguments: [@doctrine.orm.entity_manager, @service_container,"%configuration.dir.ical%"]

   mycp_accommodation_batchProcess:
       class: MyCp\mycpBundle\Helpers\AccommodationExcelReader
       arguments: [ @doctrine.orm.entity_manager, @service_container, "%configuration.dir.accommodation.batch.process.excels%" ]