parameters:

services:
#    mycp.example:
#        class: %mycp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


   abuc.job.listener:
       class: Abuc\RemarketingBundle\Event\UserSignInEventListener
       arguments: [@abuc_remarketing.job.manager, "2 min"]
       tags:
           - { name: kernel.event_listener, event: abuc.events.user.signin,  method: onUserSignInEvent }

   mycp.job.payment.confirmation.listener:
       class: Abuc\RemarketingBundle\Event\SimpleEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.accommodation.payment.confirmation"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.accommodation.payment.confirmation,  method: onEvent }
