parameters:

services:
   mycp.job.user.signupreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "abuc.job.labels.signupreminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: abuc.event.user.signup,  method: onEvent }

   mycp.job.reservation.reminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.reminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.sent_out,  method: onEvent }

   mycp.job.reservation.last.reminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.last.reminder", "42 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.sent_out,  method: onEvent }

   mycp.job.reservation.expired.offer.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.expired.offer.reminder", "48 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.sent_out,  method: onEvent }

   mycp.service.email_manager:
       class: MyCp\mycpBundle\Helpers\EmailManager
       arguments: [@doctrine.orm.entity_manager, @Email, @templating, @translator, @router, @mailer, @swiftmailer.transport.real, @logger, "noreply@mycasaparticular.com", "MyCasaParticular.com", "3"]

   mycp.job.user.latesignupreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.latesignup.reminder", "48 hours"]
       tags:
           - { name: kernel.event_listener, event: abuc.event.user.signup,  method: onEvent }

   mycp.job.user.fullcart.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.fullcart.reminder", "3 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.cart.full,  method: onEvent }

   mycp.job.user.feedback.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.feedback.reminder"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.feedback,  method: onEvent }

   mycp.service.export_to_excel:
       class: MyCp\mycpBundle\Helpers\ExportToExcel
       arguments: [@doctrine.orm.entity_manager, @service_container,"%configuration.dir.excels%"]

   mycp.service.zip:
        class: MyCp\mycpBundle\Helpers\ZipService
        arguments: [@doctrine.orm.entity_manager,@service_container, %ownership.dir.photos.zips%, %ownership.dir.photos%, %ownership.dir.photos.originals%, %user.dir.photos%]

   mycp.service.calendar:
       class: MyCp\mycpBundle\Helpers\CalendarManager
       arguments: [@doctrine.orm.entity_manager, @service_container,"%configuration.dir.ical%"]

   mycp_accommodation_batchProcess:
       class: MyCp\mycpBundle\Helpers\AccommodationExcelReader
       arguments: [ @doctrine.orm.entity_manager, @service_container, "%configuration.dir.accommodation.batch.process.excels%", @log ]

   mycp_sync_payment:
       class: MyCp\mycpBundle\Service\PaymentSyncService
       arguments: [@doctrine.orm.entity_manager,@logger, @front_end.services.booking,"%mailServer%", "%syncEmail%", "%syncEmailPassword%"]

   mycp.job.postpayment.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.postpayment.reminder", "1 hour"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.postpayment,  method: onEvent }
# <service id="security.rememberme.token.provider.in_memory" class="%security.rememberme.token.provider.in_memory.class%" public="false" />
   mycp.security.rememberme.token.provider:
       class: MyCp\mycpBundle\Security\Core\Authentication\RememberMe\MyCpBackendTokenProvider
       public: false

   mycp.notification.service:
       class: MyCp\mycpBundle\Service\NotificationService
       arguments: [@doctrine.orm.entity_manager,"%notification_service_url%", "%notification_service_api_key%", @Time, "%notification_send_sms%", "%notification_test_environment%", "%notification_test_mobile%", "%sms_contact_phone%", "%sms_contact_mobile%", @mycp.logger, "%notification_send_checkings_sms%", "%notification_send_confirmation_sms%", "%notification_send_inmediatebooking_sms%"]

   mycp.notification.mail.service:
       class: MyCp\mycpBundle\Service\NotificationMailService
       arguments: ["%notification_service_url%", "%notification_service_api_key%"]

   mycp.job.casamodule.inscription.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.casamodule.inscription.reminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: mycp.event.casamodule.newregister,  method: onEvent }

   mycp.newsletter.service:
       class: MyCp\mycpBundle\Service\NewsletterService
       arguments: [@mycp.notification.service, @mycp.notification.mail.service, @doctrine.orm.entity_manager, @templating, "%newsletter_testing_mode%", "%newsletter_testing_email%", "%newsletter_testing_mobile%"]
