parameters:

services:
   mycp.job.user.signupreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "abuc.job.labels.signupreminder", "24 hours"]
       tags:
           - { name: kernel.event_listener, event: abuc.event.user.signup,  method: onEvent }

   mycp.job.reservation.bookingreminder.listener:
       class: Abuc\RemarketingBundle\Event\DefaultEventListener
       arguments: [@abuc_remarketing.job.manager, "mycp.job.reservation.bookingreminder", "1 min"] # TODO: change "2 min" to "24 hours"
       tags:
           - { name: kernel.event_listener, event: mycp.event.reservation.bookingreminder,  method: onEvent }

   mycp.service.email_manager:
       class: MyCp\mycpBundle\Helpers\EmailManager
       arguments: [@doctrine.orm.entity_manager, @Email, @templating, @translator, @router, @mailer, @swiftmailer.transport.real, @logger, "noreply@mycasaparticular.com", "MyCasaParticular.com", "3"]
