#Rounting PARTNER-HOME
#Home PARTNER
frontend_partner_home:
    locales:  { en: "/welcome", es: "/bienvenido", de: "/willkommen" }
    defaults: { _controller: PartnerBundle:Frontend:index }

#Printing language and currency in navbar
frontend_partner_navbar:
    locales:  { en: "/navbar/{route}/{routeParams}", es: "/navbar/{route}/{routeParams}", de: "/navbar/{route}/{routeParams}" }
    defaults: { _controller: PartnerBundle:Frontend:navBar }

#Login content
frontend_partner_logincontent:
    locales:  { en: "/login/content", es: "/login/content", de: "/login/content" }
    defaults: { _controller: PartnerBundle:Frontend:contentLogin }

#Register content
frontend_partner_registercontent:
    locales:  { en: "/register/content", es: "/register/content", de: "/register/content" }
    defaults: { _controller: PartnerBundle:Frontend:contentRegister }

#Register agency
frontend_partner_registeragency:
    locales:  { en: "/register/agency", es: "/registrar/agencia", de: "/register/agency" }
    defaults: { _controller: PartnerBundle:Frontend:registerAgency }

#Activate account
frontend_partner_activateacount:
    locales:  { en: "/activateaccount/{token}", es: "/activateaccount/{token}", de: "/activateaccount/{token}" }
    defaults: { _controller: PartnerBundle:Security:activateAccount }

#Register account page
frontend_partner_registeracountpage:
    locales:  { en: "/registeraccount", es: "/cuentaregistrada", de: "/registeraccount" }
    defaults: { _controller: PartnerBundle:Frontend:registerAccountPage }

#Rounting PARTNER-BACKEND
backend_partner_dashboard:
    locales:  { en: "/dashboard", es: "/dashboard", de: "/dashboard" }
    defaults: { _controller: PartnerBundle:Backend:index }
