#Rounting PARTNER-HOME
#Home PARTNER
frontend_partner_home:
    locales:  { en: "/welcome", es: "/bienvenido", de: "/willkommen" }
    defaults: { _controller: PartnerBundle:Frontend:index }

#Printing language and currency in navbar
frontend_partner_navbar:
    locales:  { en: "/navbar/{route}/{routeParams}", es: "/navbar/{route}/{routeParams}", de: "/navbar/{route}/{routeParams}" }
    defaults: { _controller: PartnerBundle:Frontend:navBar }

#Login content
frontend_partner_logincontent:
    locales:  { en: "/login/content", es: "/login/content", de: "/login/content" }
    defaults: { _controller: PartnerBundle:Frontend:contentLogin }

#Register content
frontend_partner_registercontent:
    locales:  { en: "/register/content", es: "/register/content", de: "/register/content" }
    defaults: { _controller: PartnerBundle:Frontend:contentRegister }

#Forgot Password
frontend_partner_forgopassword:
    locales:  { en: "/forgot_password", es: "/forgot_password", de: "/forgot_password" }
    defaults: { _controller: PartnerBundle:Frontend:contentForgot }

frontend_partner_restore_password_user:
    locales:  { en: "/restore-password/", es: "/restaurar-clave/", de: "/passwort-wiederherstellen/" }
    defaults: { _controller: PartnerBundle:Security:restorePassword }

frontend_partner_change_password_user:
    locales:  { en: "/change-password/{string}/{token}", es: "/cambiar-clave/{string}/{token}", de: "/passwort-aendern/{string}/{token}" }
    defaults: { _controller: PartnerBundle:Security:changePassword }

#Register agency
frontend_partner_registeragency:
    locales:  { en: "/register/agency", es: "/registrar/agencia", de: "/register/agency" }
    defaults: { _controller: PartnerBundle:Frontend:registerAgency }

#Activate account
frontend_partner_activateacount:
    locales:  { en: "/activateaccount/{token}", es: "/activateaccount/{token}", de: "/activateaccount/{token}" }
    defaults: { _controller: PartnerBundle:Security:activateAccount }

#Register account page
frontend_partner_registeracountpage:
    locales:  { en: "/registeraccount", es: "/cuentaregistrada", de: "/registeraccount" }
    defaults: { _controller: PartnerBundle:Frontend:registerAccountPage }

#Rounting PARTNER-BACKEND
backend_partner_dashboard:
    locales:  { en: "/dashboard", es: "/dashboard", de: "/dashboard" }
    defaults: { _controller: PartnerBundle:Backend:index }

backend_partner_seacrh:
    locales:  { en: "/dashboard/search", es: "/dashboard/buscar", de: "/dashboard/search" }
    defaults: { _controller: PartnerBundle:Backend:search }

partner_dashboard_booking_pending:
    locales:  { en: "/dashboard/booking/pending", es: "/dashboard/booking/pending", de: "/dashboard/booking/pending" }
    defaults: { _controller: PartnerBundle:Dashboard:indexBookingPending }

partner_dashboard_booking_list_pending:
    locales:  { en: "/dashboard/booking/pending/list", es: "/dashboard/booking/pending/list", de: "/dashboard/booking/pending/list" }
    defaults: { _controller: PartnerBundle:Dashboard:listBookingPending }

partner_dashboard_booking_availability:
    locales:  { en: "/dashboard/booking/availability", es: "/dashboard/booking/availability", de: "/dashboard/booking/availability" }
    defaults: { _controller: PartnerBundle:Dashboard:indexBookingAvailability }

partner_dashboard_booking_list_availability:
    locales:  { en: "/dashboard/booking/availability/list", es: "/dashboard/booking/availability/list", de: "/dashboard/booking/availability/list" }
    defaults: { _controller: PartnerBundle:Dashboard:listBookingAvailability }

partner_dashboard_booking_notavailability:
    locales:  { en: "/dashboard/booking/notavailability", es: "/dashboard/booking/notavailability", de: "/dashboard/booking/notavailability" }
    defaults: { _controller: PartnerBundle:Dashboard:indexBookingNotavailability }

partner_dashboard_booking_list_notavailability:
    locales:  { en: "/dashboard/booking/notavailability/list", es: "/dashboard/booking/notavailability/list", de: "/dashboard/booking/notavailability/list" }
    defaults: { _controller: PartnerBundle:Dashboard:listBookingNotavailability }

partner_dashboard_booking_beaten:
    locales:  { en: "/dashboard/booking/beaten", es: "/dashboard/booking/beaten", de: "/dashboard/booking/beaten" }
    defaults: { _controller: PartnerBundle:Dashboard:indexBookingBeaten }

partner_dashboard_booking_list_beaten:
    locales:  { en: "/dashboard/booking/beaten/list", es: "/dashboard/booking/beaten/list", de: "/dashboard/booking/beaten/list" }
    defaults: { _controller: PartnerBundle:Dashboard:listBookingBeaten }

partner_dashboard_booking_reserved:
    locales:  { en: "/dashboard/booking/reserved", es: "/dashboard/booking/reserved", de: "/dashboard/booking/reserved" }
    defaults: { _controller: PartnerBundle:Dashboard:indexBookingReserved }

partner_dashboard_booking_list_reserved:
    locales:  { en: "/dashboard/booking/reserved/list", es: "/dashboard/booking/reserved/list", de: "/dashboard/booking/reserved/list" }
    defaults: { _controller: PartnerBundle:Dashboard:listBookingReserved }

partner_dashboard_booking_canceled:
    locales:  { en: "/dashboard/booking/canceled", es: "/dashboard/booking/canceled", de: "/dashboard/booking/canceled" }
    defaults: { _controller: PartnerBundle:Dashboard:indexBookingCanceled }

partner_dashboard_booking_list_canceled:
    locales:  { en: "/dashboard/booking/canceled/list", es: "/dashboard/booking/canceled/list", de: "/dashboard/booking/canceled/list" }
    defaults: { _controller: PartnerBundle:Dashboard:listBookingCanceled }

partner_dashboard_booking_checkin:
    locales:  { en: "/dashboard/booking/checkin", es: "/dashboard/booking/checkin", de: "/dashboard/booking/checkin" }
    defaults: { _controller: PartnerBundle:Dashboard:indexBookingCheckin }

partner_dashboard_booking_list_checkin:
    locales:  { en: "/dashboard/booking/checkin/list", es: "/dashboard/booking/checkin/list", de: "/dashboard/booking/checkin/list" }
    defaults: { _controller: PartnerBundle:Dashboard:listBookingCheckin }
