<?php

namespace MyCp\PartnerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use MyCp\mycpBundle\Entity\generalReservation;

/**
 * paInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paInvoiceRepository extends EntityRepository {

    function getLastCreatedDatePartner()
    {
        $em = $this->getEntityManager();
        $queryString = "SELECT i.filename 
       FROM PartnerBundle:paInvoice i
       WHERE i.id = (SELECT MAX(e.id) FROM PartnerBundle:paInvoice e)
        
        ";

        $query = $em->createQuery($queryString);

        $data = $query->getArrayResult();
        return  $data;
    }

}
