<?php

namespace MyCp\PartnerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * paPendingPaymentAgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paPendingPaymentAgencyRepository extends EntityRepository {

}
