<?php

namespace MyCp\PartnerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * paTourOperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paTourOperatorRepository extends EntityRepository {
    /**
     * @return array
     */
    public function getOwners()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT us FROM mycpBundle:user us join PartnerBundle:paTourOperator pat 
        Where us.user_id = pat.tourOperator");
        return $query->getResult();
    }

}
