<?php

namespace MyCp\PartnerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use MyCp\mycpBundle\Entity\user;

/**
 * paTravelAgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paTravelAgencyRepository extends EntityRepository {

    /**
     * @param $obj
     * @param $file
     * @param $factory
     * @param $send_creation_mail
     * @param $controller
     * @param $container
     */
    public function createUser($obj, $file, $factory, $send_creation_mail, $controller, $container){
        $em = $this->getEntityManager();
        $agency = $em->getRepository('PartnerBundle:paTravelAgency')->find($obj->getId());
        $dir_file = $container->getParameter('user.dir.photos');
        $photoSize = $container->getParameter('user.photo.size');
        $user = new user();
            $country = $em->getRepository('mycpBundle:country')->findBy(array('co_name' => 'Cuba'));
            $subrole = $em->getRepository('mycpBundle:role')->findOneBy(array('role_name' => 'ROLE_CLIENT_CASA'));

            $address = $obj->getOwnAddressStreet() . " #" . $obj->getOwnAddressNumber() . ", " . $obj->getOwnAddressMunicipality()->getMunName() . ", " . $obj->getOwnAddressProvince()->getProvName();
            $phone = '(+53) ' . $obj->getOwnAddressProvince()->getProvPhoneCode() . ' ' . $obj->getOwnPhoneNumber();

            $email = $obj->getOwnEmail1();
            if (empty($email))
                $email = $obj->getOwnEmail2();

            $user->setUserAddress($address);
            $user->setUserCity($obj->getOwnAddressMunicipality()->getMunName());
            $user->setUserCountry($country[0]);
            $user->setUserEmail($email);
            $user->setUserPhone($phone);
            $user->setUserName($obj->getOwnMcpCode());

            if ($file) {
                $photo = new photo();
                $fileName = uniqid('user-') . '-photo.jpg';
                $file->move($dir_file, $fileName);
                //Redimensionando la foto del usuario
                \MyCp\mycpBundle\Helpers\Images::resize($dir_file . $fileName, $photoSize);
                $photo->setPhoName($fileName);
                $user->setUserPhoto($photo);
                $em->persist($photo);
            }

            $user->setUserRole('ROLE_CLIENT_CASA');
            $user->setUserEnabled(false);
            $user->setUserCreatedByMigration(false);
            $user->setUserSubrole($subrole);
            $user_name = explode(' ', $obj->getOwnHomeOwner1());
            $user->setUserUserName($user_name[0]);
            $lastName = (count($user_name) > 1) ? $user_name[1] : "";
            $user->setUserLastName($lastName);
            $user->setUserPassword(" ");

            $user_casa = new userCasa();
            $user_casa->setUserCasaOwnership($obj);
            $user_casa->setUserCasaUser($user);
            $encoder = $factory->getEncoder($user);
            $secret_token = $encoder->encodePassword("casa_" . $obj->getOwnMcpCode(), $user->getSalt());
            $secret_token = base64_encode($secret_token);
            $secret_token = str_replace('/', '1', $secret_token);
            $secret_token = str_replace(' ', '2', $secret_token);
            $secret_token = str_replace('+', '3', $secret_token);
            $secret_token = str_replace('=', '4', $secret_token);
            $secret_token = str_replace('?', '5', $secret_token);
            $user_casa->setUserCasaSecretToken($secret_token);
            $em->persist($user);
            $em->persist($user_casa);*/

        if ($send_creation_mail) {
            $user = $user_casa->getUserCasaUser();
            \MyCp\mycpBundle\Helpers\UserMails::sendCreateUserCasaMailNew($controller, $user->getUserEmail(), $user->getName(), $user->getUserUserName() . ' ' . $user->getUserLastName(), $user_casa->getUserCasaSecretToken(), $obj->getOwnName(), $obj->getOwnMcpCode());
        }

        return $user_casa;
    }
}
